In [1]:
import numpy as np

## Problem A.23

### Part a.

Let us calculate the commutator of $\textbf{M}$ with its Hermitian conjugate:

$$
\textbf{M} \textbf{M}^{\dagger} - \textbf{M}^{\dagger} \textbf{M} = \left( \begin{matrix}
1 & 1 \\
1 & i
\end{matrix} \right) \left( \begin{matrix}
1 & 1 \\
1 & -i
\end{matrix} \right) - \left( \begin{matrix}
1 & 1 \\
1 & -i
\end{matrix} \right) \left( \begin{matrix}
1 & 1 \\
1 & i
\end{matrix} \right)
$$

$$
\textbf{M} \textbf{M}^{\dagger} - \textbf{M}^{\dagger} \textbf{M} = \left( \begin{matrix}
2 & 1 - i \\
1 + i & 2 \\
\end{matrix} \right) - \left( \begin{matrix}
2 & 1 + i \\
1 & 2 \\
\end{matrix} \right)
$$

$$
\textbf{M} \textbf{M}^{\dagger} - \textbf{M}^{\dagger} \textbf{M} = \left( \begin{matrix}
0 & -2i \\
2i & 0 \\
\end{matrix} \right)
$$

So $\textbf{M}$ is not normal.

#### Numerical tests

In [2]:
M = np.array([[1, 1], [1, 1j]])
M @ np.matrix.getH(M) - np.matrix.getH(M) @ M

array([[0.+0.j, 0.-2.j],
       [0.+2.j, 0.+0.j]])

### Part b.

First we need to find the eigenvalues:

$$
\left| \begin{matrix}
1 - \lambda & 1 \\
1 & i - \lambda \\
\end{matrix} \right| = 0
$$

$$
\begin{eqnarray}
\implies (1 - \lambda) (i - \lambda) - 1 & = & 0 \\
\implies \lambda^2 - (1 + i) \lambda - 1 + i & = & 0 \\
\implies \lambda & = & \frac{1}{2} \left( 1 + i \pm \sqrt{(1 + i)^2  +4 (1 - i)} \right) \\
\implies \lambda & = & \frac{1}{2} \left( 1 + i \pm \sqrt{4 - 2i} \right)
\end{eqnarray}
$$

The first eigenvector is then given by the solution to the equation

$$
\begin{eqnarray}
v_1^{(1)} + v_2^{(1)} & = & \frac{1}{2} \left( 1 + i + \sqrt{4 - 2i} \right) v_1^{(1)} \\
\implies v_2^{(1)} & = & \frac{1}{2} \left( -1 + i + \sqrt{4 - 2i} \right) v_1^{(1)}
\end{eqnarray}
$$

The second eigenvector is then

$$
\begin{eqnarray}
v_1^{(2)} + i v_2^{(2)} & = & \frac{1}{2} \left( 1 + i - \sqrt{4 - 2i} \right) v_2^{(2)} \\
\implies v_1^{(2)} & = & \frac{1}{2} \left(1 - i - \sqrt{4 - 2i} \right) v_2^{(2)}
\end{eqnarray}
$$

The inverse of the similarity matrix is then:

$$
\textbf{S}^{-1} = \left( \begin{matrix}
1 & -\frac{1}{2} \left(1 - i - \sqrt{4 - 2i} \right) \\
\frac{1}{2} \left(1 - i - \sqrt{4 - 2i} \right) & 1 \\
\end{matrix} \right)
$$

The determinant of this matrix is

$$
\begin{eqnarray}
\textrm{det}(\textbf{S}^{-1}) & = & 1 + \frac{1}{4} \left( 1 - i - \sqrt{4 - 2i} \right)^2 \\
& = & 1 + \frac{1}{4} \left( -2i + 4 - 2i - 2(1 - i) \sqrt{4 - 2i} \right) \\
& = & 1 + 1 - i - \frac{1}{2} (1 - i) \sqrt{4 - 2i} \\
& = & 2 - i - \frac{1}{2} (1 - i) \sqrt{4 - 2i} \\
\end{eqnarray}
$$

Since this determinant is non-zero, the matrix $\textbf{S}$ exists and the matrix $\textbf{M}$ is diagonalizable.

#### Numerical tests

In [3]:
np.linalg.eigvals(M)

array([ 1.52908551+0.25706586j, -0.52908551+0.74293414j])

In [4]:
(-1 + 1j + np.sqrt(4 - 2j)) / 2

(0.5290855136357462+0.2570658641216772j)

In [5]:
(1 - 1j - np.sqrt(4 - 2j)) / 2

(-0.5290855136357462-0.2570658641216772j)

In [6]:
eigvectors = np.linalg.eig(M)[1]
eigvectors /= eigvectors[0, 0]
eigvectors

array([[ 1.        +0.j        , -0.52908551-0.25706586j],
       [ 0.52908551+0.25706586j,  1.        +0.j        ]])

In [7]:
np.linalg.det(eigvectors.T)

(1.2138486222425766+0.2720196495140689j)

In [8]:
2 - 1j - 1 / 2 * (1 - 1j) * np.sqrt(4 - 2j)

(1.2138486222425766+0.272019649514069j)