In [1]:
import numpy as np

## Problem A.9

### Part a.

$$
\textbf{A} \textbf{a} = \left( \begin{matrix}
-1 & 1 & i \\
2 & 0 & 3 \\
2i & -2i & 2 \\
\end{matrix} \right) \left( \begin{matrix}
i \\
2i \\
2 \\
\end{matrix} \right) = \left( \begin{matrix}
3i \\
6 + 2 i \\
6 \\
\end{matrix} \right)
$$

In [2]:
A = np.array([[-1, 1, 1j], [2, 0, 3], [2j, -2j, 2]])
B = np.array([[2, 0, -1j], [0, 1, 0], [1j, 3, 2]])

a = np.array([[1j], [2j], [2]])
b = np.array([[2], [1 - 1j], [0]])

np.matmul(A, a)

array([[0.+3.j],
       [6.+2.j],
       [6.+0.j]])

### Part b.

$$
\textbf{a}^{\dagger} \textbf{b} = \left( \begin{matrix}
-i & -2i & 2 \\ \end{matrix} \right) \left( \begin{matrix}
2 \\
1 - i \\
0 \\
\end{matrix} \right) = -2i - 2i - 2 = -2 - 4i
$$

In [3]:
np.dot(np.conj(a.T), b)

array([[-2.-4.j]])

### Part c.

$$
\tilde{\textbf{a}} \textbf{B} \textbf{b} = \left( \begin{matrix}
i & 2i & 2 \end{matrix} \right) \left( \begin{matrix}
2 & 0 & -i \\
0 & 1 & 0 \\
i & 3 & 2 \\
\end{matrix} \right) \left( \begin{matrix}
2 \\
1 - i \\
0 \\
\end{matrix} \right) = \left( \begin{matrix}
i & 2i & 2 \end{matrix} \right) \left( \begin{matrix}
4 \\
1 - i \\
3 - i \\
\end{matrix} \right) = 8 + 4i
$$

In [4]:
np.matmul(a.T, np.matmul(B, b))

array([[8.+4.j]])

### Part d.

$$
\textbf{a} \textbf{b}^{\dagger} = \left( \begin{matrix}
i \\
2i \\
2 \\
\end{matrix} \right) \left( \begin{matrix}
2 & 1 + i & 0 \\
\end{matrix} \right) = \left( \begin{matrix}
2i & -1 + i & 0 \\
4i & -2 + 2i & 0 \\
4 & 2 + 2i & 0 \\
\end{matrix} \right)
$$

In [5]:
np.matmul(a, np.conj(b.T))

array([[ 0.+2.j, -1.+1.j,  0.+0.j],
       [ 0.+4.j, -2.+2.j,  0.+0.j],
       [ 4.+0.j,  2.+2.j,  0.+0.j]])