In [1]:
import numpy as np

## Problem A.25

### Part a.

$$
\textbf{T}^{\dagger} = \left( \begin{matrix}
1 & 1 - i \\
1 + i & 0 \\
\end{matrix} \right) = \textbf{T}
$$

#### Numerical tests

In [2]:
T = np.array([[1, 1-1j], [1+1j, 0]])

In [3]:
np.all(np.conj(T.T) == T)

True

### Part b.

The eigenvalues are found by solving the following equation:

$$
\left| \begin{matrix}
1 - \lambda & 1 - i \\
1 + i & -\lambda
\end{matrix} \right| = 0
$$

$$
\begin{eqnarray}
\implies \lambda^2 - \lambda - (1 - i)(1 + i) & = & 0 \\
\implies \lambda^2 - \lambda - 2 & = & 0 \\
\implies \lambda & = & \frac{1}{2} \left( 1 \pm \sqrt{1 + 8} \right) \\
\implies \lambda & \in & \{-1, 2\}
\end{eqnarray}
$$

#### Numerical tests

In [4]:
np.linalg.eig(T)[0]

array([ 2.+1.04672831e-16j, -1.-1.04672831e-16j])

### Part c.

The eigenvector associated with the eigenvalue 2 is given by the solution to the equation

$$
\left( \begin{matrix}
1 & 1 - i \\
1 + i & 0
\end{matrix} \right) \left( \begin{matrix}
v_1 \\
v_2
\end{matrix} \right) = 2 \left( \begin{matrix}
v_1 \\
v_2
\end{matrix} \right)
$$

This implies the following system of equations:

$$
\begin{eqnarray}
v_1 + (1 - i) v_2 & = & 2 v_1 \\
(1 + i) v_1 = 2 v_2
\end{eqnarray}
$$

This yields the unnormalized eigenvector:

$$
\textbf{v}^{(2)} = \left( \begin{matrix}
1 \\
\frac{1}{2} (1 + i)
\end{matrix} \right)
$$

Normalizing yields

$$
\hat{\textbf{v}}^{(2)} = \left( \begin{matrix}
\sqrt{\frac{2}{3}} \\
\frac{1 + i}{\sqrt{6}}
\end{matrix} \right)
$$

The eigenvector associated with the eigenvalue -1 is given by the solution to the system of equations:

$$
\begin{eqnarray}
v_1 + (1 - i) v_2 & = & -v_1 \\
(1 + i) v_1 = -v_2
\end{eqnarray}
$$

This yields the unnormalized eigenvector

$$
\textbf{v}^{(-1)} = \left( \begin{matrix}
1 \\
-1 - i
\end{matrix} \right)
$$

Normalizing yields

$$
\hat{\textbf{v}}^{(-1)} = \left( \begin{matrix}
\frac{1}{\sqrt{3}} \\
-\frac{1 + i}{\sqrt{3}}
\end{matrix} \right)
$$

#### Numerical tests

In [5]:
np.linalg.eig(T)[1]

array([[ 0.81649658+0.j        , -0.40824829+0.40824829j],
       [ 0.40824829+0.40824829j,  0.81649658+0.j        ]])

In [6]:
np.array([np.sqrt(2 / 3), (1 + 1j) / np.sqrt(6)])

array([0.81649658+0.j        , 0.40824829+0.40824829j])

In [7]:
np.array([1 / np.sqrt(3), -(1 + 1j) / np.sqrt(3)])

array([ 0.57735027+0.j        , -0.57735027-0.57735027j])

In [8]:
np.abs(1 / (np.linalg.eig(T)[1][0, 1] * np.sqrt(3)))

0.9999999999999998

In [9]:
np.linalg.eig(T)[1][:, 1] / (np.linalg.eig(T)[1][0, 1] * np.sqrt(3))

array([ 0.57735027+0.j        , -0.57735027-0.57735027j])

### Part d.

The inverse of the diagonalizing matrix is

$$
\textbf{S}^{-1} = \left( \begin{matrix}
\sqrt{\frac{2}{3}} & \frac{1}{\sqrt{3}} \\
\frac{1 + i}{\sqrt{6}} & -\frac{1 + i}{\sqrt{3}}
\end{matrix} \right)
$$

Now calculating $\textbf{S}$ we have

$$
\textbf{S} = \left( -\frac{\sqrt{2}}{3}(1 + i) - \frac{1}{3 \sqrt{2}} (1 + i) \right)^{-1} \left( \begin{matrix}
-\frac{1 + i}{\sqrt{3}} & -\frac{1}{\sqrt{3}} \\
-\frac{1 + i}{\sqrt{6}} & \sqrt{\frac{2}{3}}
\end{matrix} \right)
$$

So we have

$$
\textbf{S} = - \frac{\sqrt{2}}{1 + i} \left( \begin{matrix}
-\frac{1 + i}{\sqrt{3}} & -\frac{1}{\sqrt{3}} \\
\frac{1 + i}{\sqrt{6}} & \sqrt{\frac{2}{3}}
\end{matrix} \right)
$$

which reduces to

$$
\textbf{S} = \left( \begin{matrix}
\sqrt{\frac{2}{3}} & \frac{1 - i}{\sqrt{6}} \\
\frac{1}{\sqrt{3}} & -\frac{1 - i}{\sqrt{3}}
\end{matrix} \right)
$$

#### Numerical tests

In [10]:
Sinv = np.array([[np.sqrt(2 / 3), 1 / np.sqrt(3)], [(1 + 1j) / np.sqrt(6), -(1 + 1j) / np.sqrt(3)]])

In [11]:
S = np.linalg.inv(Sinv)
S

array([[ 0.81649658+0.j        ,  0.40824829-0.40824829j],
       [ 0.57735027+0.j        , -0.57735027+0.57735027j]])

In [12]:
np.array([[np.sqrt(2 / 3), (1 - 1j) / np.sqrt(6)], [1 / np.sqrt(3), -(1 - 1j) / np.sqrt(3)]])

array([[ 0.81649658+0.j        ,  0.40824829-0.40824829j],
       [ 0.57735027+0.j        , -0.57735027+0.57735027j]])

#### Analytic tests

Now let's check that we can use $\textbf{S}$ to diagonalize $\textbf{T}$:

$$
\textbf{S}\textbf{T}\textbf{S}^{-1} = \left( \begin{matrix}
\sqrt{\frac{2}{3}} & \frac{1 - i}{\sqrt{6}} \\
\frac{1}{\sqrt{3}} & -\frac{1 - i}{\sqrt{3}}
\end{matrix} \right) \left( \begin{matrix}
1 & 1 - i \\
1 + i & 0
\end{matrix} \right) \left( \begin{matrix}
\sqrt{\frac{2}{3}} & \frac{1}{\sqrt{3}} \\
\frac{1 + i}{\sqrt{6}} & -\frac{1 + i}{\sqrt{3}}
\end{matrix} \right)
$$

$$
\textbf{S}\textbf{T}\textbf{S}^{-1} = \left( \begin{matrix}
\frac{2 \sqrt{2}}{\sqrt{3}} & \sqrt{\frac{2}{3}}(1 - i) \\
-\frac{1}{\sqrt{3}} & \frac{1 - i}{\sqrt{3}}
\end{matrix} \right) \left( \begin{matrix}
\sqrt{\frac{2}{3}} & \frac{1}{\sqrt{3}} \\
\frac{1 + i}{\sqrt{6}} & -\frac{1 + i}{\sqrt{3}}
\end{matrix} \right)
$$

$$
\textbf{S}\textbf{T}\textbf{S}^{-1} = \left( \begin{matrix}
2 & 0 \\
0 & -1
\end{matrix} \right)
$$

### Part e.

We have

$$
\textrm{Tr}(\textbf{T}) = 1
$$

and

$$
\textrm{det}(\textbf{T}) = -2
$$

in both the original form and the diagonalized form.