In [1]:
import numpy as np

## Problem A.18

To find the eigenvalues we must solve the following determinant:

$$
\begin{vmatrix}
\cos \theta - \lambda & -\sin \theta \\
\sin \theta & \cos \theta - \lambda \\
\end{vmatrix} = 0
$$

This implies that we must find the $\lambda$ that satisfies the equation

$$
(\cos \theta - \lambda)^2  +\sin^2 \theta = 0
$$

$$
\implies \lambda^2 - 2 \lambda \cos \theta + 1 = 0
$$

$$
\begin{eqnarray}
\implies \lambda & = & \frac{1}{2} \left(2 \cos \theta \pm \sqrt{4 \cos^2 \theta - 4} \right) \\
& = & \cos \theta \pm \sqrt{\cos^2 \theta - 1} \\
& = & \cos \theta \pm \sqrt{- \sin^2 \theta} \\
& = & \cos \theta \pm i \sin \theta
\end{eqnarray}
$$

Thus we only have a real solution iff $\sin \theta = 0$, which means that we must have $\theta \in \{0, \pi\}$.

We can simplify the general case of complex eigenvalues with $\lambda = e^{\pm i \theta}$.  To find the eigenvectors, we have in the positive case

$$
\left( \begin{matrix}
\cos \theta & -\sin \theta \\
\sin \theta & \cos \theta \\
\end{matrix} \right) \left( \begin{matrix}
v_1 \\
v_2 \\
\end{matrix} \right) = e^{i \theta} \left( \begin{matrix}
v_1 \\
v_2 \\
\end{matrix} \right)
$$
This implies the following set of equations:
$$
\begin{eqnarray}
\cos \theta v_1 - \sin \theta v_2 & = & e^{i \theta} v_1 \\
\sin \theta v_1 + \cos \theta v_2 & = & e^{i \theta} v_2
\end{eqnarray}
$$
$$
\begin{eqnarray}
\implies v_1 & = & - \frac{\sin \theta v_2}{e^{i \theta} - \cos \theta} \\
& = & -\frac{v_2}{i} \\
& = & i v_2
\end{eqnarray}
$$
And so the first eigenvector is
$$
a^{(1)} = \frac{1}{\sqrt{2}} \left( \begin{matrix}
1 \\
-i
\end{matrix} \right)
$$
To find the second eigenvector, we now have
$$
\left( \begin{matrix}
\cos \theta & -\sin \theta \\
\sin \theta & \cos \theta \\
\end{matrix} \right) \left( \begin{matrix}
v_1 \\
v_2 \\
\end{matrix} \right) = e^{-i \theta} \left( \begin{matrix}
v_1 \\
v_2 \\
\end{matrix} \right)
$$
which similarly implies
$$
\begin{eqnarray}
\cos \theta v_1 - \sin \theta v_2 & = & e^{-i \theta} v_1 \\
\sin \theta v_1 + \cos \theta v_2 & = & e^{-i \theta} v_2
\end{eqnarray}
$$
$$
\begin{eqnarray}
\implies v_1 & = & - \frac{\sin \theta v_2}{e^{-i \theta} - \cos \theta} \\
& = & \frac{v_2}{i} \\
& = & -i v_2
\end{eqnarray}
$$
And so the second eigenvector is
$$
a^{(2)} = \frac{1}{\sqrt{2}} \left( \begin{matrix}
1 \\
i
\end{matrix} \right)
$$

### Numerical tests

In [2]:
theta = 0.3
R = np.array([[np.cos(theta), -np.sin(theta)], [np.sin(theta), np.cos(theta)]])

a1 = np.array([1, -1j]) / np.sqrt(2)
a2 = np.array([1, 1j]) / np.sqrt(2)

In [3]:
np.matmul(R, a1)

array([0.67552491+0.20896434j, 0.20896434-0.67552491j])

In [4]:
np.exp(1j * theta) * a1

array([0.67552491+0.20896434j, 0.20896434-0.67552491j])

In [5]:
np.matmul(R, a2)

array([0.67552491-0.20896434j, 0.20896434+0.67552491j])

In [6]:
np.exp(-1j * theta) * a2

array([0.67552491-0.20896434j, 0.20896434+0.67552491j])

### Continuing the problem...

Now to find the similarity matrix $\textbf{S}$ we note that the matrix $\textbf{S}^{-1}$ has columns which are the eigenvectors:

$$
\textbf{S}^{-1} = \frac{1}{\sqrt{2}} \left( \begin{matrix}
1 & 1 \\
-i & i \\
\end{matrix} \right)
$$

The determinant of $\textbf{S}^{-1}$ is

$$
\textrm{det}(\textbf{S}^{-1}) = i
$$

so the matrix $\textbf{S}$ is

$$
\textbf{S} = \frac{1}{\sqrt{2}} \left( \begin{matrix}
1 & i \\
1 & -i
\end{matrix} \right)
$$

The diagonalization of $\textbf{T}$ will be

$$
\textbf{S} \textbf{T} \textbf{S}^{-1} = \frac{1}{2} \left( \begin{matrix}
1 & i \\
1 & -i
\end{matrix} \right) \left( \begin{matrix}
\cos \theta & -\sin \theta \\
\sin \theta & \cos \theta \\
\end{matrix} \right) \left( \begin{matrix}
1 & 1 \\
-i & i \\
\end{matrix} \right)
$$

$$
\textbf{S} \textbf{T} \textbf{S}^{-1} = \frac{1}{2} \left( \begin{matrix}
1 & i \\
1 & -i
\end{matrix} \right) \left( \begin{matrix}
\cos \theta + i \sin \theta & \cos \theta - i \sin \theta \\
\sin \theta - i \cos \theta & \sin \theta + i \cos \theta
\end{matrix} \right)
$$

$$
\textbf{S} \textbf{T} \textbf{S}^{-1} = \frac{1}{2} \left( \begin{matrix}
1 & i \\
1 & -i
\end{matrix} \right) \left( \begin{matrix}
e^{i \theta} & e^{-i \theta} \\
-i e^{i \theta} & i e^{-i \theta}
\end{matrix} \right)
$$

$$
\textbf{S} \textbf{T} \textbf{S}^{-1} = \left( \begin{matrix}
e^{i \theta} & 0 \\
0 & e^{-i \theta}
\end{matrix} \right)
$$