In [1]:
import numpy as np

## Problem A.8

In [2]:
A = np.array([[-1, 1, 1j], [2, 0, 3], [2j, -2j, 2]])
B = np.array([[2, 0, -1j], [0, 1, 0], [1j, 3, 2]])

### Part a.

$$
\textbf{A} + \textbf{B} = \left(
\begin{matrix}
1 & 1 & 0 \\
2 & 1 & 3 \\
3i & 3 - 2i & 4 \\
\end{matrix} \right)
$$

In [3]:
A + B

array([[1.+0.j, 1.+0.j, 0.+0.j],
       [2.+0.j, 1.+0.j, 3.+0.j],
       [0.+3.j, 3.-2.j, 4.+0.j]])

### Part b.

$$
\textbf{A} \textbf{B} = \left(
\begin{matrix}
-3 & 1 + 3i & 3i \\
4 + 3i & 9 & 6 - 2i \\
6i & 6 - 2i & 6 \\
\end{matrix} \right)
$$

In [4]:
A @ B

array([[-3.+0.j,  1.+3.j,  0.+3.j],
       [ 4.+3.j,  9.+0.j,  6.-2.j],
       [ 0.+6.j,  6.-2.j,  6.+0.j]])

### Part c.

$$
\textbf{B} \textbf{A} = \left(
\begin{matrix}
0 & 0 & 0 \\
2 & 0 & 3 \\
6 + 3i & -3i & 12 \\
\end{matrix} \right)
$$

This implies that

$$
\left[ \textbf{A}, \textbf{B} \right] = \left(
\begin{matrix}
-3 & 1 + 3i & 3i \\
2 + 3i & 9 & 3 - 2i \\
-6 + 3i & 6 + i & -6 \\
\end{matrix}
\right)
$$

In [5]:
A@B - B@A

array([[-3.+0.j,  1.+3.j,  0.+3.j],
       [ 2.+3.j,  9.+0.j,  3.-2.j],
       [-6.+3.j,  6.+1.j, -6.+0.j]])

### Part d.

$$
\tilde{\textbf{A}} = \left(
\begin{matrix}
-1 & 2 & 2i \\
1 & 0 & -2i \\
i & 3 & 2 \\
\end{matrix} \right)
$$

In [6]:
np.transpose(A)

array([[-1.+0.j,  2.+0.j,  0.+2.j],
       [ 1.+0.j,  0.+0.j, -0.-2.j],
       [ 0.+1.j,  3.+0.j,  2.+0.j]])

### Part e.

$$
\textbf{A}^* = \left(
\begin{matrix}
-1 & 1 & -i \\
2 & 0 & 3 \\
-2i & 2i & 2 \\
\end{matrix} \right)
$$

In [7]:
np.conj(A)

array([[-1.-0.j,  1.-0.j,  0.-1.j],
       [ 2.-0.j,  0.-0.j,  3.-0.j],
       [ 0.-2.j, -0.+2.j,  2.-0.j]])

### Part f.

$$
\textbf{A}^\dagger = \left(
\begin{matrix}
-1 & 2 & -2i \\
1 & 0 & 2i \\
-i & 3 & 2 \\
\end{matrix} \right)
$$

In [8]:
np.matrix.getH(A)

array([[-1.-0.j,  2.-0.j,  0.-2.j],
       [ 1.-0.j,  0.-0.j, -0.+2.j],
       [ 0.-1.j,  3.-0.j,  2.-0.j]])

### Part g.

$$
\textrm{det}(\textbf{B}) = 
2 \left| \begin{matrix} 1 & 0 \\ 3 & 2 \end{matrix} \right|
-i \left| \begin{matrix} 0 & 1 \\ i & 3 \end{matrix} \right|
= 4 - 1 = 3
$$

In [9]:
np.linalg.det(B)

(2.9999999999999996+0j)

### Part h.

The matrix of cofactors is given by

$$
\textbf{C} = \left( \begin{matrix}
2 & 0 & -i \\
-3i & 5 & -6 \\
i & 0 & 2 \\
\end{matrix} \right)
$$

and so the inverse is

$$
\textbf{B}^{-1} = \frac{1}{3} \left( \begin{matrix}
2 & -3i & i \\
0 & 3 & 0 \\
-i & -6 & 2 \\
\end{matrix} \right)
$$

We have

$$
\textbf{B}^{-1} \textbf{B} = \frac{1}{3} \left( \begin{matrix}
2 & -3i & i \\
0 & 3 & 0 \\
-i & -6 & 2 \\
\end{matrix} \right) \left( \begin{matrix}
2 & 0 & -i \\
0 & 1 & 0 \\
i & 3 & 2 \\
\end{matrix} \right)
= \left( \begin{matrix}
1 & 0 & 0 \\
0 & 1 & 0 \\
0 & 0 & 1 \\
\end{matrix} \right)
$$

as required.

In [10]:
np.linalg.inv(B)

array([[ 0.66666667+0.j        ,  0.        -1.j        ,
         0.        +0.33333333j],
       [ 0.        +0.j        ,  1.        +0.j        ,
         0.        +0.j        ],
       [ 0.        -0.33333333j, -2.        -0.j        ,
         0.66666667+0.j        ]])

$\textbf{A}$ does not have an inverse because its determinant is zero:

$$
\textrm{det}(\textbf{A}) = - \left| \begin{matrix} 0 & 3 \\ -2i & 1 \end{matrix} \right|
- \left| \begin{matrix} 2 & 3 \\ 2i & 2 \end{matrix} \right|
+ i \left| \begin{matrix} 2 & 0 \\ 2i & -2i \\ \end{matrix} \right|
= -6i -4 + 6i + 4 = 0
$$

In [11]:
np.linalg.det(A)

0j