In [1]:
import numpy as np

## Problem A.14

### Part a.

$$
\textbf{R}_1 = \left( \begin{matrix}
\cos \theta & -\sin \theta & 0 \\
\sin \theta & \cos \theta & 0 \\
0 & 0 & 1
\end{matrix} \right)
$$

### Part b.

This matrix will rotate the $x$-axis into the $y$-axis, the $y$-axis into the $z$-axis, and the $z$-axis into the $x$-axis:
$$
\textbf{R}_2 = \left( \begin{matrix}
0 & 0 & 1 \\
1 & 0 & 0 \\
0 & 1 & 0 \\
\end{matrix} \right)
$$

### Part c.

$$
\textbf{R}_3 = \left( \begin{matrix}
1 & 0 & 0 \\
0 & 1 & 0 \\
0 & 0 & -1 \\
\end{matrix} \right)
$$

### Part d.

$$
\textbf{R}_1 \tilde{\textbf{R}}_1 = \left( \begin{matrix}
\cos \theta & -\sin \theta & 0 \\
\sin \theta & \cos \theta & 0 \\
0 & 0 & 1
\end{matrix} \right) \left( \begin{matrix}
\cos \theta & \sin \theta & 0 \\
-\sin \theta & \cos \theta & 0 \\
0 & 0 & 1
\end{matrix} \right) = \left( \begin{matrix}
\cos^2 \theta + \sin^2 \theta & \cos \theta \sin \theta - \cos \theta \sin \theta & 0 \\
\cos \theta \sin \theta - \cos \theta \sin \theta & \cos^2 \theta + \sin^2 \theta & 0 \\
0 & 0 & 1 \\
\end{matrix} \right) = \left( \begin{matrix}
1 & 0 & 0 \\
0 & 1 & 0 \\
0 & 0 & 1 \\
\end{matrix} \right)
$$

$$
\textrm{det}(\textbf{R}_1) = \cos^2 \theta + \sin^2 \theta = 1
$$

$$
\textbf{R}_2 \tilde{\textbf{R}}_2 = \left( \begin{matrix}
0 & 0 & 1 \\
1 & 0 & 0 \\
0 & 1 & 0 \\
\end{matrix} \right) \left( \begin{matrix}
0 & 1 & 0 \\
0 & 0 & 1 \\
1 & 0 & 0 \\
\end{matrix} \right) = \left( \begin{matrix}
1 & 0 & 0 \\
0 & 1 & 0 \\
0 & 0 & 1 \\
\end{matrix} \right)
$$

$$
\textrm{det}(\textbf{R}_2) = 1
$$

$$
\textbf{R}_3 \tilde{\textbf{R}}_3 = \left( \begin{matrix}
1 & 0 & 0 \\
0 & 1 & 0 \\
0 & 0 & -1 \\
\end{matrix} \right) \left( \begin{matrix}
1 & 0 & 0 \\
0 & 1 & 0 \\
0 & 0 & -1 \\
\end{matrix} \right) = \left( \begin{matrix}
1 & 0 & 0 \\
0 & 1 & 0 \\
0 & 0 & 1 \\
\end{matrix} \right)
$$

$$
\textrm{det}(\textbf{R}_3) = -1
$$

In [2]:
def R1(theta):
    return np.array([
        [np.cos(theta), -np.sin(theta), 0],
        [np.sin(theta), np.cos(theta), 0],
        [0, 0, 1]
    ])

In [3]:
R1(.123) @ R1(.123).T

array([[ 1.00000000e+00, -1.95932709e-18,  0.00000000e+00],
       [-1.95932709e-18,  1.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00,  1.00000000e+00]])

In [4]:
np.linalg.det(R1(.123))

1.0

In [5]:
R2 = np.array([
    [0, 0, 1],
    [1, 0, 0],
    [0, 1, 0]
])

In [6]:
R2 @ R2.T

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [7]:
np.linalg.det(R2)

1.0

In [8]:
R3 = np.array([
    [1, 0, 0],
    [0, 1, 0],
    [0, 0, -1]
])

In [9]:
R3 @ R3.T

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [10]:
np.linalg.det(R3)

-1.0