In [1]:
import numpy as np

## Problem A.15

$$
\textbf{T}_x = \left( \begin{matrix}
1 & 0 & 0 \\
0 & \cos \theta & -\sin \theta \\
0 & \sin \theta & \cos \theta \\
\end{matrix} \right)
$$

$$
\textbf{T}_y = \left( \begin{matrix}
-\cos \theta & 0 & \sin \theta \\
0 & 1 & 0 \\
-\sin \theta & 0 & \cos \theta \\
\end{matrix} \right)
$$

$$
\textbf{S} = \left( \begin{matrix}
0 & -1 & 0 \\
1 & 0 & 0 \\
0 & 0 & 1 \\
\end{matrix} \right)
$$

$$
\textbf{S} \textbf{T}_x \textbf{S}^{-1} = \left( \begin{matrix}
0 & -1 & 0 \\
1 & 0 & 0 \\
0 & 0 & 1 \\
\end{matrix} \right) \left( \begin{matrix}
1 & 0 & 0 \\
0 & \cos \theta & -\sin \theta \\
0 & \sin \theta & \cos \theta \\
\end{matrix} \right) \left( \begin{matrix}
0 & 1 & 0 \\
-1 & 0 & 0 \\
0 & 0 & 1 \\
\end{matrix} \right)
$$

$$
\implies \textbf{S} \textbf{T}_x \textbf{S}^{-1} = \left( \begin{matrix}
0 & -\cos \theta & \sin \theta \\
1 & 0 & 0 \\
0 & \sin \theta & \cos \theta \\
\end{matrix} \right) \left( \begin{matrix}
0 & 1 & 0 \\
-1 & 0 & 0 \\
0 & 0 & 1 \\
\end{matrix} \right)
$$

$$
\implies \textbf{S} \textbf{T}_x \textbf{S}^{-1} = \left( \begin{matrix}
\cos \theta & 0 & \sin \theta \\
0 & 1 & 0 \\
-\sin \theta & 0 & \cos \theta \\
\end{matrix} \right)
$$

This transformation is therefore equivalent to reflecting about the $x$-axis and then rotating by $-\theta$ about the $y$-axis.

Now for $\textbf{T}_y$:

$$
\textbf{S} \textbf{T}_y \textbf{S}^{-1} = \left( \begin{matrix}
0 & -1 & 0 \\
1 & 0 & 0 \\
0 & 0 & 1 \\
\end{matrix} \right) \left( \begin{matrix}
-\cos \theta & 0 & \sin \theta \\
0 & 1 & 0 \\
-\sin \theta & 0 & \cos \theta \\
\end{matrix} \right) \left( \begin{matrix}
0 & 1 & 0 \\
-1 & 0 & 0 \\
0 & 0 & 1 \\
\end{matrix} \right)
$$

$$
\implies \textbf{S} \textbf{T}_y \textbf{S}^{-1} = \left( \begin{matrix}
0 & -1 & 0 \\
-\cos \theta & 0 & \sin \theta \\
-\sin \theta & 0 & \cos \theta \\
\end{matrix} \right) \left( \begin{matrix}
0 & 1 & 0 \\
-1 & 0 & 0 \\
0 & 0 & 1 \\
\end{matrix} \right)
$$

$$
\implies \textbf{S} \textbf{T}_y \textbf{S}^{-1} = \left( \begin{matrix}
1 & 0 & 0 \\
0 & -\cos \theta & \sin \theta \\
0 & -\sin \theta & \cos \theta \\
\end{matrix} \right)
$$

This transformation is therefore equivalent to reflecting about the $y$-axis and rotating by $-\theta$ about the $x$-axis.

In [2]:
S = np.array([
    [0, -1, 0],
    [1, 0, 0],
    [0, 0, 1]
])

theta = 0.123

Tx = np.array([
    [1, 0, 0],
    [0, np.cos(theta), -np.sin(theta)],
    [0, np.sin(theta), np.cos(theta)],
])

Ty = np.array([
    [-np.cos(theta), 0, np.sin(theta)],
    [0, 1, 0],
    [-np.sin(theta), 0, np.cos(theta)],
])

In [3]:
S @ Tx

array([[ 0.        , -0.99244503,  0.12269009],
       [ 1.        ,  0.        ,  0.        ],
       [ 0.        ,  0.12269009,  0.99244503]])

In [4]:
S @ Tx @ np.linalg.inv(S)

array([[ 0.99244503,  0.        ,  0.12269009],
       [ 0.        ,  1.        ,  0.        ],
       [-0.12269009,  0.        ,  0.99244503]])

In [5]:
S @ Ty

array([[ 0.        , -1.        ,  0.        ],
       [-0.99244503,  0.        ,  0.12269009],
       [-0.12269009,  0.        ,  0.99244503]])

In [6]:
S @ Ty @ np.linalg.inv(S)

array([[ 1.        ,  0.        ,  0.        ],
       [ 0.        , -0.99244503,  0.12269009],
       [ 0.        , -0.12269009,  0.99244503]])