In [1]:
import numpy as np

## Problem A.28

### Part a.

#### Part i.

We have tbat

$$
\textbf{M}^2 = \left( \begin{matrix}
0 & 1 & 3 \\
0 & 0 & 4 \\
0 & 0 & 0 \\
\end{matrix} \right) \left( \begin{matrix}
0 & 1 & 3 \\
0 & 0 & 4 \\
0 & 0 & 0 \\
\end{matrix} \right) = \left( \begin{matrix}
0 & 0 & 4 \\
0 & 0 & 0 \\
0 & 0 & 0 \\
\end{matrix} \right)
$$

Furthermore,

$$
\textbf{M}^3 = \left( \begin{matrix}
0 & 0 & 4 \\
0 & 0 & 0 \\
0 & 0 & 0 \\
\end{matrix} \right) \left( \begin{matrix}
0 & 1 & 3 \\
0 & 0 & 4 \\
0 & 0 & 0 \\
\end{matrix} \right) = \left( \begin{matrix}
0 & 0 & 0 \\
0 & 0 & 0 \\
0 & 0 & 0 \\
\end{matrix} \right)
$$

This implies that all terms of order $\textbf{M}^3$ and higher are zero and do not contribute to the series.  We therefore have

$$
e^{\textbf{M}} = \left( \begin{matrix}
1 & 0 & 0 \\
0 & 1 & 0 \\
0 & 0 & 1 \\
\end{matrix} \right) + \left( \begin{matrix}
0 & 1 & 3 \\
0 & 0 & 4 \\
0 & 0 & 0 \\
\end{matrix} \right) + \frac{1}{2} \left( \begin{matrix}
0 & 0 & 4 \\
0 & 0 & 0 \\
0 & 0 & 0 \\
\end{matrix} \right) = \left( \begin{matrix}
1 & 1 & 5 \\
0 & 1 & 4 \\
0 & 0 & 1 \\
\end{matrix} \right)
$$

##### Numerical tests

In [2]:
M = np.array([[0, 1, 3], [0, 0, 4], [0, 0, 0]])

In [3]:
M @ M

array([[0, 0, 4],
       [0, 0, 0],
       [0, 0, 0]])

In [4]:
M @ M @ M

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [5]:
np.eye(3) + M + M @ M / 2

array([[1., 1., 5.],
       [0., 1., 4.],
       [0., 0., 1.]])

#### Part ii.

We have that

$$
\textbf{M}^2 = \left( \begin{matrix}
0 & \theta \\
-\theta & 0 \\
\end{matrix} \right) \left( \begin{matrix}
0 & \theta \\
-\theta & 0 \\
\end{matrix} \right) = \left( \begin{matrix}
-\theta^2 & 0 \\
0 & -\theta^2 \\
\end{matrix} \right) = -\theta^2 \textbf{I}.
$$

This now implies that

$$
\textbf{M}^3 = -\theta^2 \textbf{M}.
$$

Generalizing to an arbitrary even order term, we have

$$
\textbf{M}^{2n} = (-1)^n \theta^{2n} \textbf{I},
$$

and generalizing to an arbitrary odd order term,

$$
\textbf{M}^{2n + 1} = (-1)^n \theta^{2n} \textbf{M}.
$$

Now inserting these terms into the Taylor expansion,

$$
e^{\textbf{M}} = \sum_{n=0}^{\infty} (-1)^n \frac{\theta^{2n}}{n!} \left( \begin{matrix}
1 & 0 \\
0 & 1 \\
\end{matrix} \right)
+ \sum_{n=0}^{\infty} (-1)^n \frac{\theta^{2n + i}}{n!} \left( \begin{matrix}
0 & 1 \\
-1 & 0 \\
\end{matrix} \right)
$$

Recognizing that these sums are the Taylor series for sine and cosine, we find

$$
e^{\textbf{M}} = \left( \begin{matrix}
\cos \theta & \sin \theta \\
-\sin \theta & \cos \theta
\end{matrix} \right)
$$

### Part b.

Let us suppose that the eigenvalues of the matrix $\textbf{M}$ are given by $\lambda_i$ and the eigenvalues of $e^{\textbf{M}}$ are given by $\lambda^{\prime}_i$.  This means that

$$
\textrm{det}(e^{\textbf{M}}) = \prod_i \lambda_i^{\prime}.
$$

Now let us suppose that the diagonalized version of $\textbf{M}$ is written $\textbf{M}^{\prime}$.  This means that

$$
e^{\textbf{M}^{\prime}} = \sum_{n=0}^{\infty} \frac{\textbf{M}^{\prime n}}{n!}
$$

since every term in this series is a diagonal matrix, this means that $e^{\textbf{M}^{\prime}}$ is diagonal as well.

Furthermore, note that if $\textbf{S}$ diagonalizes $\textbf{M}$, then it must diagonalize $e^{\textbf{M}}$ as well, since

$$
\begin{eqnarray}
e^{\textbf{M}^{\prime}} & = & e^{\textbf{S} \textbf{M} \textbf{S}^{-1}} \\
& = & \sum_{n=0}^{\infty} \frac{(\textbf{S} \textbf{M} \textbf{S}^{-1})^n}{n!} \\
& = & \textbf{S} \left( \sum_{n=0}^{\infty} \frac{\textbf{M}^n}{n!} \right) \textbf{S}^{-1} \\
& = & \textbf{S} e^{\textbf{M}} \textbf{S}^{-1}
\end{eqnarray}
$$

This then means that the eigenvalues of $e^{\textbf{M}}$, $\lambda^{\prime}$ are the same as the eigenvalues of $e^{\textbf{M}^{\prime}}$.  But because $e^{\textbf{M}^{\prime}}$ is diagonal, its eigenvalues are

$$
\begin{eqnarray}
\lambda_i^{\prime} & = & \sum_{n=0}^{\infty} \frac{\lambda_i^n}{n!} \\
& = & e^{\lambda_i}
\end{eqnarray}
$$

Putting this together with the first equation, we have

$$
\begin{eqnarray}
\textrm{det}\left( e^{\textbf{M}} \right) & = & \prod_i e^{\lambda_i} \\
& = & e^{\sum_i \lambda_i}
\end{eqnarray}
$$

But the sum of the eigenvalues is just the trace of the matrix.  So we have

$$
\textrm{det}\left( e^{\textbf{M}} \right) = e^{\textrm{Tr}(\textbf{M})}.
$$

### Part c.

Let us first consider $e^{\textbf{M} + \textbf{N}}$:

$$
\begin{eqnarray}
e^{\textbf{M} + \textbf{N}}
 & = & \sum_{n=0}^{\infty} \frac{(\textbf{M} + \textbf{N})^n}{n!} \\
 & = & \sum_{n=0}^{\infty} \sum_{k=0}^n {n \choose k} \frac{\textbf{M}^k \textbf{N}^{n-k}}{n!} \\
 & = & \sum_{n=0}^{\infty} \sum_{k=0}^n \frac{\textbf{M}^k \textbf{N}^{n-k}}{k! (n - k)!} \\
\end{eqnarray}
$$

where we take advantage of the commutation of the matrices to group them together.

Now consider the product $e^{\textbf{M}} e^{\textbf{N}}$:

$$
\begin{eqnarray}
e^{\textbf{M}} e^{\textbf{N}}
 & = & \left( \sum_{n=0}^{\infty} \frac{\textbf{M}^n}{n!} \right) \left( \sum_{m=0}^{\infty} \frac{\textbf{N}^m}{m!} \right) \\
 & = & \sum_{n=0}^{\infty} \sum_{m=0}^{\infty} \frac{\textbf{M}^n \textbf{N}^m}{n!}{m!} \\
\end{eqnarray}
$$
Let us now introduce $k \equiv n - m$.  This means that $m = n - k$.  The second summation can now be indexed with $k$ instead of $m$, but the lower limit of $m = 0$ now translates to an upper limit of $k = n$.  Because the summand now has terms with indices from both sums, the upper limit of $\infty$ in the second summation translates into a lower limit of 0 (higher order terms are now captured by the first summation).  This means we have

$$
e^{\textbf{M}} e^{\textbf{N}} = \sum_{n=0}^{\infty} \sum_{k=0}^n \frac{\textbf{M}^k \textbf{N}^{n-k}}{k! (n - k)!}
$$

And so

$$
e^{\textbf{M} + \textbf{N}} = e^{\textbf{M}} e^{\textbf{N}}
$$

For a counterexample when the matrices do not commute, consider

$$
\textbf{M} = \left( \begin{matrix}
0 & 1 \\
0 & 0 \\
\end{matrix} \right)
$$
and
$$
\textbf{N} = \left( \begin{matrix}
0 & 0 \\
-1 & 0 \\
\end{matrix} \right)
$$

In both cases the square is zero, so we have

$$
e^{\textbf{M}} = \left( \begin{matrix}
1 & 1 \\
0 & 1 \\
\end{matrix} \right)
$$
and
$$
e^{\textbf{N}} = \left( \begin{matrix}
1 & 0 \\
-1 & 0 \\
\end{matrix} \right)
$$

This now means that

$$
e^{\textbf{M}} e^{\textbf{N}} = \left( \begin{matrix}
0 & 1 \\
-1 & 1 \\
\end{matrix} \right)
$$

But now consider $e^{\textbf{M} + \textbf{N}}$:

$$
e^{\textbf{M} + \textbf{N}} = \sum_{n=0}^{\infty} \frac{1}{n!} \left( \begin{matrix}
0 & 1 \\
-1 & 0 \\
\end{matrix} \right)^n
$$
But we found in Part a. ii. that this is
$$
e^{\textbf{M} + \textbf{N}} = \left( \begin{matrix}
\cos 1 & \sin 1 \\
-\sin 1 & \cos 1
\end{matrix} \right)
$$
which is not equal to $e^{\textbf{M}}e^{\textbf{N}}$.

### Part d.

We have that

$$
e^{i \textbf{H}} = \sum_{n=0}^{\infty} \frac{(i \textbf{H})^n}{n!}
$$

Now consider the adjoint:

$$
\begin{eqnarray}
\left( e^{i \textbf{H}} \right)^{\dagger}
 & = & \left( \sum_{n=0}^{\infty} \frac{(i \textbf{H})^n}{n!} \right)^{\dagger} \\
 & = & \sum_{n=0}^{\infty} \frac{(-i \textbf{H})^n}{n!} \\
 & = & e^{-i \textbf{H}}
\end{eqnarray}
$$

But now note that $\textbf{H}$ commutes with itself, so we have

$$
e^{i\textbf{H}} e^{-i \textbf{H}} = \textbf{I}
$$

which means that the adjoint $e^{-i \textbf{H}}$ is the inverse of $e^{i \textbf{H}}$.  Hence $e^{i \textbf{H}}$ is unitary.