# Appendix

In [1]:
import numpy as np

Invisible Latex commands are in this cell.

$$\newcommand{\ket}[1]{\left|{#1}\right\rangle}$$
$$\newcommand{\bra}[1]{\left\langle{#1}\right|}$$
$$\newcommand{\braket}[2]{\left\langle{#1}\middle|{#2}\right\rangle}$$
$$\newcommand{\norm}[1]{\left\lVert#1\right\rVert}$$

## Problem A.1

### Part a.

Yes, the subset of all vectors with $a_z = 0$ is a vector space.  Since the the original set is a vector space, the properties of vector addition and multiplication all hold, but we must show that the subspace is closed.  Here, note that the sum of any two vectors in the subspace will have $a_z = 0$ as well since the sum can be done component-wise.  Furthermore, scalar multiplication is closed since we can again perform the operation component-wise and this will maintain $a_z = 0$.  Finally, the null vector is in this subspace since the null vector has $a_z = 0$, and the inverse vectors are in the subspace since the inverses can be found component-wise and $-0 = 0 = a_z$.

The dimension of the subspace is 2 since it is spanned by the basis vectors $\hat{i}$ and $\hat{j}$.

### Part b.

The subspace of all vectors with $a_z = 1$ is not a subspace because it is not closed under vector addition or scalar multiplication.  For example, $2 \cdot \hat{k}$ is not in the subspace even though $\hat{k}$ is.  Furthermore the subspace does not have a null vector since the null vector must have $a_z = 0$.

### Part c.

The subset of all vectors whose components are all equal is a vector space.

Consider $\textbf{a} = a \hat{i} + a \hat{j} + a \hat{k}$ and $\textbf{b} = b \hat{i} + b \hat{j} + b \hat{k}$.  Then $\textbf{a} + \textbf{b} = (a + b) \hat{i} + (a + b) \hat{j} + (a + b) \hat{k}$.  All the components are equal, so the vector stays in the subspace.  Similarly, $c \textbf{a} = ca \hat{i} + ca \hat{j} + ca \hat{k}$.  All the components are equal so the vector stays in the subspace.  Thus the subspace is closed under addition and multiplication.  Finally, the null vector exists in this subspace and the inverse vectors all also have the same components and so exist in the subspace.

## Problem A.2

### Part a.

This set is a vector space.  The sum of two polynomials of degree $N$ is also a polynomial of degree $N$ or less, so the set is closed under addition.  Multiplying a polynomial of degree $N$ by a scalar is also a polynomial of degree $N$ or less, so the set is closed under multiplication.  Furthermore, $0$ exists as a null vector, and the inverse vectors also exist by taking the coefficients of the polynomials and multilpying them by $-1$.

### Part b.

The set of even polynomials is also a vector space since the sum of two even polynomials is also an even polynomial (nor does multiplication by a scalar change the evenness of the polynomial).  Furthermore this subset contains the null vector and every inverse vector.

### Part c.

The subset of polynomials with the leading coefficient equal to 1 is not a vector space since the sum of two such polynomials has a leading coefficient equal to 2 and is therefore not in the space.

### Part d.

The subset of polynomials with the value 0 at $x = 1$ is a vector space.  We can write such polynomials as

$$
a = (x - 1) \sum_{i = 0}^{N - 1} a_i x^i
$$

Now, the sum of two such polynomials is

\begin{eqnarray}
\textbf{a} + \textbf{b} & = & (x - 1) \sum_{i = 0}^{N - 1} a_i x^i + (x - 1) \sum_{i = 0}^{N - 1} b_i x^i \\
 & = & (x - 1) \sum_{i = 0}^{N - 1} (a_i + b_i) x^i
\end{eqnarray}

and so is closed under vector addition.  Similarly, multiplying such a polynomial by a scalar results in

\begin{eqnarray}
c \textbf{a} & = & c (x - 1) \sum_{i = 0}^{N - 1} a_i x^i \\
& = & (x - 1) \sum_{i = 0}^{N - 1} (c a_i) x^i
\end{eqnarray}

and so is closed under scalar multiplication.  The space contains the null vector since setting the $a_i = 0$ results in a polynomial which is 0 at $x = 1$.  Finally, the space contains all inverse vectors by setting the coefficients equal to $-a_i$.

### Part e.

The subset of polynomials with the value 1 at $x = 0$ is not a vector space since it does not contain the null vector nor is it closed under addition since the sum of two such polynomials will have the value 2 at $x = 0$.

## Problem A.3

We may write the vector $\ket{\alpha}$ as

$$
\ket{\alpha} = \sum_i a_i \ket{e_i}
$$

Now, suppose there were some other component representation in this basis.  Then we could write 

$$
\ket{\alpha} = \sum_i b_i \ket{e_i}
$$

with $a_i \neq b_i$ for some $i$.  But now consider the difference between these two representations:

$$
\sum_i a_i \ket{e_i} - \sum_i b_i \ket{e_i} = \sum_i (a_i - b_i) \ket{e_i} \neq 0
$$

since by assumption there is some component that is different.  But we must have that this difference equals zero since $\ket{\alpha} - \ket{\alpha} = 0$ and the null vector has zeros in all components.

## Problem A.4

$$
\norm{e_1} = 2
$$

$$
\ket{e_1^{\prime}} = \frac{1}{2}(1 + i) \hat{i} + \frac{1}{2} \hat{j} + \frac{i}{2} \hat{k}
$$

$$
\braket{e_1^{\prime}}{e_2} = \frac{i}{2} (1 - i) + \frac{3}{2} - \frac{i}{2} = \frac{1}{2}(i + 1 - 3 - i) = 2
$$

$$
\ket{e_2} - \braket{e_1^{\prime}}{e_2} = i \hat{i} + 3 \hat{j} + \hat{k} - 2((1 + i) \hat{i} + \hat{j} + i \hat{k}) 
= -\hat{i} + 2 \hat{j} + (1 - i) \hat{k}
$$

$$
\norm{\ket{e_2} - \braket{e_1^{\prime}}{e_2}} = \sqrt{1 + 4 + 2} = \sqrt{7}
$$

$$
\ket{e_2^{\prime}} = -\frac{1}{\sqrt{7}} \hat{i} + \frac{2}{\sqrt{7}} \hat{j} + \frac{1 - i}{\sqrt{7}} \hat{k}
$$

$$
\braket{e_1^{\prime}}{e_3} = 14
$$

$$
\braket{e_2^{\prime}}{e_3} = 8 \sqrt{7}
$$

$$
\ket{e_3} - \braket{e_1^{\prime}}{e_3} - \braket{e_2^{\prime}}{e_3} =
28 \hat{j} - 7((1 + i) \hat{i} + \hat{j} + i \hat{k}) - 8(-\hat{i} + 2\hat{j} + (1 - i) \hat{k}) =
(1 - 7i) \hat{i} + 5 \hat{j} + (-8 + i)\hat{k}
$$

$$
\norm{\ket{e_3} - \braket{e_1^{\prime}}{e_3} - \braket{e_2^{\prime}}{e_3}} = \sqrt{140}
$$

$$
\ket{e_3^{\prime}} = \frac{1}{2 \sqrt{35}} ((1 - 7i) \hat{i} + 5 \hat{j} + (-8 + i) \hat{k})
$$

In [2]:
e1 = np.array([1 + 1j, 1, 1j])
e2 = np.array([1j, 3, 1])
e3 = np.array([0, 28, 0])

In [3]:
e1prime = e1 / np.linalg.norm(e1)
e1prime

array([0.5+0.5j, 0.5+0.j , 0. +0.5j])

In [4]:
e2prime = (e2 - np.vdot(e1prime, e2) * e1prime) / np.linalg.norm(e2 - np.vdot(e1prime, e2) * e1prime)

In [5]:
np.allclose(e2prime, np.array([-1 / np.sqrt(7), 2 / np.sqrt(7), (1 - 1j) / np.sqrt(7)]))

True

In [6]:
e3prime = ((e3 - np.vdot(e1prime, e3) * e1prime - np.vdot(e2prime, e3) * e2prime) /
    np.linalg.norm(e3 - np.vdot(e1prime, e3) * e1prime - np.vdot(e2prime, e3) * e2prime))

In [7]:
np.allclose(e3prime, 1 / (2 * np.sqrt(35)) * np.array([1 - 7j, 5, -8 + 1j]))

True

## Problem A.5

Let

$$
\ket{\gamma} \equiv \ket{\beta} - \frac{\braket{\alpha}{\beta}}{\braket{\alpha}{\alpha}} \ket{\alpha}.
$$

Now consider the norm of $\gamma$:

\begin{eqnarray}
\braket{\gamma}{\gamma} & = & \left( \bra{\beta} - \frac{\braket{\beta}{\alpha}}{\braket{\alpha}{\alpha}} \bra{\alpha} \right) \left( \ket{\beta} - \frac{\braket{\alpha}{\beta}}{\braket{\alpha}{\alpha}} \ket{\alpha} \right) \\
& = & \braket{\beta}{\beta} - \frac{\braket{\alpha}{\beta}}{\braket{\alpha}{\alpha}} \braket{\beta}{\alpha} - \frac{\braket{\beta}{\alpha}}{\braket{\alpha}{\alpha}} \braket{\alpha}{\beta} + \frac{\braket{\beta}{\alpha} \braket{\alpha}{\beta}}{\braket{\alpha}{\alpha}^2} \braket{\alpha}{\alpha} \\
& = & \braket{\beta}{\beta} + \frac{\braket{\beta}{\alpha} \braket{\alpha}{\beta}}{\braket{\alpha}{\alpha}}
\end{eqnarray}

Now, note that $\braket{\gamma}{\gamma} \geq 0$, so

$$
\braket{\alpha}{\alpha} \braket{\beta}{\beta} \geq \left| \braket{\alpha}{\beta} \right|^2
$$

as required.

## Problem A.6

$$
\braket{\alpha}{\beta} = (1 - i)(4 - i) - i(2 - 2i) = 1 - 7i
$$

$$
\braket{\beta}{\alpha} = 1 + 7i
$$

$$
\braket{\alpha}{\alpha} = 4
$$

$$
\braket{\beta}{\beta} = 25
$$

$$
\cos \theta = \sqrt{\frac{(1 + 7i)(1 - 7i)}{4 \times 25}} = \frac{1}{\sqrt{2}}
$$

And so $\theta = \pi / 4$.

In [8]:
alpha = np.array([1 + 1j, 1, 1j])
beta = np.array([4 - 1j, 0, 2 - 2j])

In [9]:
np.allclose(
    np.pi / 4, 
    np.arccos(np.sqrt(np.vdot(alpha, beta) * np.vdot(beta, alpha) /
                      (np.linalg.norm(alpha)**2 * np.linalg.norm(beta)**2))),
)

True

## Problem A.7

\begin{eqnarray}
\norm{\ket{\alpha} + \ket{\beta}}^2 & = & \left( \bra{\alpha} + \bra{\beta} \right) \left(\ket{\alpha} + \ket{\beta}\right) \\
& = & \braket{\alpha}{\alpha} + \braket{\beta}{\beta} + \braket{\alpha}{\beta} + \braket{\beta}{\alpha} \\
& = & \norm{\alpha}^2 + \norm{\beta}^2 + \braket{\alpha}{\beta} + \braket{\alpha}{\beta}^*
\end{eqnarray}

Now note that by the Schwarz inequality $|\braket{\alpha}{\beta}| \leq \norm{\alpha} \norm{\beta}$.  This implies that

\begin{eqnarray}
\norm{\ket{\alpha} + \ket{\beta}}^2 & \leq & \norm{\alpha}^2 + \norm{\beta}^2 + 2 \norm{\alpha} \norm{\beta} \\
& \leq & \left( \norm{\alpha} + \norm{\beta} \right)^2
\end{eqnarray}

Therefore $\norm{\ket{\alpha} + \ket{\beta}} \leq \norm{\alpha} + \norm{\beta}$ as required.

## Problem A.8

In [10]:
A = np.array([[-1, 1, 1j], [2, 0, 3], [2j, -2j, 2]])
B = np.array([[2, 0, -1j], [0, 1, 0], [1j, 3, 2]])

### Part a.

$$
\textbf{A} + \textbf{B} = \left(
\begin{matrix}
1 & 1 & 0 \\
2 & 1 & 3 \\
3i & 3 - 2i & 4 \\
\end{matrix} \right)
$$

In [11]:
A + B

array([[1.+0.j, 1.+0.j, 0.+0.j],
       [2.+0.j, 1.+0.j, 3.+0.j],
       [0.+3.j, 3.-2.j, 4.+0.j]])

### Part b.

$$
\textbf{A} \textbf{B} = \left(
\begin{matrix}
-3 & 1 + 3i & 3i \\
4 + 3i & 9 & 6 - 2i \\
6i & 6 - 2i & 6 \\
\end{matrix} \right)
$$

In [12]:
A @ B

array([[-3.+0.j,  1.+3.j,  0.+3.j],
       [ 4.+3.j,  9.+0.j,  6.-2.j],
       [ 0.+6.j,  6.-2.j,  6.+0.j]])

### Part c.

$$
\textbf{B} \textbf{A} = \left(
\begin{matrix}
0 & 0 & 0 \\
2 & 0 & 3 \\
6 + 3i & -3i & 12 \\
\end{matrix} \right)
$$

This implies that

$$
\left[ \textbf{A}, \textbf{B} \right] = \left(
\begin{matrix}
-3 & 1 + 3i & 3i \\
2 + 3i & 9 & 3 - 2i \\
-6 + 3i & 6 + i & -6 \\
\end{matrix}
\right)
$$

In [13]:
A@B - B@A

array([[-3.+0.j,  1.+3.j,  0.+3.j],
       [ 2.+3.j,  9.+0.j,  3.-2.j],
       [-6.+3.j,  6.+1.j, -6.+0.j]])

### Part d.

$$
\tilde{\textbf{A}} = \left(
\begin{matrix}
-1 & 2 & 2i \\
1 & 0 & -2i \\
i & 3 & 2 \\
\end{matrix} \right)
$$

In [14]:
np.transpose(A)

array([[-1.+0.j,  2.+0.j,  0.+2.j],
       [ 1.+0.j,  0.+0.j, -0.-2.j],
       [ 0.+1.j,  3.+0.j,  2.+0.j]])

### Part e.

$$
\textbf{A}^* = \left(
\begin{matrix}
-1 & 1 & -i \\
2 & 0 & 3 \\
-2i & 2i & 2 \\
\end{matrix} \right)
$$

In [15]:
np.conj(A)

array([[-1.-0.j,  1.-0.j,  0.-1.j],
       [ 2.-0.j,  0.-0.j,  3.-0.j],
       [ 0.-2.j, -0.+2.j,  2.-0.j]])

### Part f.

$$
\textbf{A}^\dagger = \left(
\begin{matrix}
-1 & 2 & -2i \\
1 & 0 & 2i \\
-i & 3 & 2 \\
\end{matrix} \right)
$$

In [16]:
np.matrix.getH(A)

array([[-1.-0.j,  2.-0.j,  0.-2.j],
       [ 1.-0.j,  0.-0.j, -0.+2.j],
       [ 0.-1.j,  3.-0.j,  2.-0.j]])

### Part g.

$$
\textrm{det}(\textbf{B}) = 
2 \left| \begin{matrix} 1 & 0 \\ 3 & 2 \end{matrix} \right|
-i \left| \begin{matrix} 0 & 1 \\ i & 3 \end{matrix} \right|
= 4 - 1 = 3
$$

In [17]:
np.linalg.det(B)

(2.9999999999999996+0j)

### Part h.

The matrix of cofactors is given by

$$
\textbf{C} = \left( \begin{matrix}
2 & 0 & -i \\
-3i & 5 & -6 \\
i & 0 & 2 \\
\end{matrix} \right)
$$

and so the inverse is

$$
\textbf{B}^{-1} = \frac{1}{3} \left( \begin{matrix}
2 & -3i & i \\
0 & 3 & 0 \\
-i & -6 & 2 \\
\end{matrix} \right)
$$

We have

$$
\textbf{B}^{-1} \textbf{B} = \frac{1}{3} \left( \begin{matrix}
2 & -3i & i \\
0 & 3 & 0 \\
-i & -6 & 2 \\
\end{matrix} \right) \left( \begin{matrix}
2 & 0 & -i \\
0 & 1 & 0 \\
i & 3 & 2 \\
\end{matrix} \right)
= \left( \begin{matrix}
1 & 0 & 0 \\
0 & 1 & 0 \\
0 & 0 & 1 \\
\end{matrix} \right)
$$

as required.

In [18]:
np.linalg.inv(B)

array([[ 0.66666667+0.j        ,  0.        -1.j        ,
         0.        +0.33333333j],
       [ 0.        +0.j        ,  1.        +0.j        ,
         0.        +0.j        ],
       [ 0.        -0.33333333j, -2.        -0.j        ,
         0.66666667+0.j        ]])

$\textbf{A}$ does not have an inverse because its determinant is zero:

$$
\textrm{det}(\textbf{A}) = - \left| \begin{matrix} 0 & 3 \\ -2i & 1 \end{matrix} \right|
- \left| \begin{matrix} 2 & 3 \\ 2i & 2 \end{matrix} \right|
+ i \left| \begin{matrix} 2 & 0 \\ 2i & -2i \\ \end{matrix} \right|
= -6i -4 + 6i + 4 = 0
$$

In [19]:
np.linalg.det(A)

0j

## Problem A.9

### Part a.

$$
\textbf{A} \textbf{a} = \left( \begin{matrix}
-1 & 1 & i \\
2 & 0 & 3 \\
2i & -2i & 2 \\
\end{matrix} \right) \left( \begin{matrix}
i \\
2i \\
2 \\
\end{matrix} \right) = \left( \begin{matrix}
3i \\
6 + 2 i \\
6 \\
\end{matrix} \right)
$$

In [20]:
a = np.array([[1j], [2j], [2]])
b = np.array([[2], [1 - 1j], [0]])

In [21]:
np.matmul(A, a)

array([[0.+3.j],
       [6.+2.j],
       [6.+0.j]])

### Part b.

$$
\textbf{a}^{\dagger} \textbf{b} = \left( \begin{matrix}
-i & -2i & 2 \\ \end{matrix} \right) \left( \begin{matrix}
2 \\
1 - i \\
0 \\
\end{matrix} \right) = -2i - 2i - 2 = -2 - 4i
$$

In [22]:
np.dot(np.conj(a.T), b)

array([[-2.-4.j]])

### Part c.

$$
\tilde{\textbf{a}} \textbf{B} \textbf{b} = \left( \begin{matrix}
i & 2i & 2 \end{matrix} \right) \left( \begin{matrix}
2 & 0 & -i \\
0 & 1 & 0 \\
i & 3 & 2 \\
\end{matrix} \right) \left( \begin{matrix}
2 \\
1 - i \\
0 \\
\end{matrix} \right) = \left( \begin{matrix}
i & 2i & 2 \end{matrix} \right) \left( \begin{matrix}
4 \\
1 - i \\
3 - i \\
\end{matrix} \right) = 8 + 4i
$$

In [23]:
np.matmul(a.T, np.matmul(B, b))

array([[8.+4.j]])

### Part d.

$$
\textbf{a} \textbf{b}^{\dagger} = \left( \begin{matrix}
i \\
2i \\
2 \\
\end{matrix} \right) \left( \begin{matrix}
2 & 1 + i & 0 \\
\end{matrix} \right) = \left( \begin{matrix}
2i & -1 + i & 0 \\
4i & -2 + 2i & 0 \\
4 & 2 + 2i & 0 \\
\end{matrix} \right)
$$

In [24]:
np.matmul(a, np.conj(b.T))

array([[ 0.+2.j, -1.+1.j,  0.+0.j],
       [ 0.+4.j, -2.+2.j,  0.+0.j],
       [ 4.+0.j,  2.+2.j,  0.+0.j]])

## Problem A.10

### Part a.

Consider an arbitrary element of the matrix $\textbf{T}$, $T_{ij}$.  In general we will have that $T_{ij} \neq T_{ji}$.  Now suppose it is possible to write $\textbf{T}$ as a sum of a symmetrix matrix $\textbf{S}$ and an antisymmetric matrix $\textbf{A}$.  Then we have

$$
\begin{eqnarray}
T_{ij} & = & S_{ij} + A_{ij}, \\
T_{ji} & = & S_{ij} - A_{ij}
\end{eqnarray}
$$

Solving for $S_{ij}$ and $A_{ij}$ we find

$$
\begin{eqnarray}
S_{ij} = \frac{1}{2} \left( T_{ij} + T_{ji} \right) \\
A_{ij} = \frac{1}{2} \left( T_{ij} - T_{ji} \right) \\
\end{eqnarray}
$$
By inspection it can be verified that $\textbf{S}$ is indeed symmetric and $\textbf{A}$ is antisymmetric.

Thus by construction it is possible to write any matrix as a sum of a symmetric and antisymmetric matrix.

### Part b.

An arbitrary term of the matrix $\textbf{T}$ can be written

$$
T_{ij} = a_{ij} + b_{ij} i.
$$

Construct a matrix $\textbf{R}$ whose components are given by $R_{ij} = a_{ij}$ and a matrix $\textbf{M}$ whose components are given by $M_{ij} = b_{ij} i$.  Then $\textbf{R}$ is a real matrix and $\textbf{M}$ is an imaginary matrix and any matrix can be written as the sum of the two.

### Part c.

Consider an arbitrary element of the matrix $\textbf{T}$, $T_{ij}$.  Suppose that it is possible to write $\textbf{T}$ as the sum of a Hermitian matrix $\textbf{H}$ and a skew-Hermitian matrix $\textbf{K}$.  Then we have

$$
\begin{eqnarray}
T_{ij} & = & H_{ij} + K_{ij} \\
T_{ji}^* & = & H_{ij} - K_{ij} \\
\end{eqnarray}
$$

Solving for $H_{ij}$ and $K_{ij}$ we find

$$
\begin{eqnarray}
H_{ij} & = & \frac{1}{2} \left( T_{ij} + T_{ji}^* \right) \\
K_{ij} & = & \frac{1}{2} \left( T_{ij} - T_{ji}^* \right)
\end{eqnarray}
$$
By inspection it can be verified that $\textbf{H}$ is indeed Hermitian and $\textbf{K}$ is skew-Hermitian.

Thus by construction it is possible to write any matrix as a sum of a Hermitian and skew-Hermitian matrix.

## Problem A.11

Let us prove that $\widetilde{\textbf{S} \textbf{T}} = \tilde{\textbf{T}} \tilde{\textbf{S}}$.  Consider an arbitrary element of $\widetilde{\textbf{S} \textbf{T}}$:

$$
\begin{eqnarray}
\left(\widetilde{\textbf{S} \textbf{T}}\right)_{ij} & = & \sum_k S_{jk} T_{ki} \\
& = & \sum_k T_{ki} S_{jk} \\
& = & \sum_k \tilde{T}_{ik} \tilde{S}_{kj} \\
& = & \left( \tilde{\textbf{T}} \tilde{\textbf{S}} \right)_{ij}
\end{eqnarray}
$$

Now let us prove that $(\textbf{ST})^{\dagger} = \textbf{T}^{\dagger} \textbf{S}^{\dagger}$.  Consider an arbitrary element:

$$
\begin{eqnarray}
\left( \textbf{ST} \right)^{\dagger}_{ij} & = & \left( \sum_k S_{ik} T_{kj} \right)^{\dagger} \\
& = & \sum_k S_{jk}^* T_{ki}^* \\
& = & \sum_k T_{ki}^* S_{jk}^* \\
& = & \left( \textbf{T}^{\dagger} \textbf{S}^{\dagger} \right)_{ij}
\end{eqnarray}
$$

Let us prove that $(\textbf{S} \textbf{T})^{-1} = \textbf{T}^{-1} \textbf{S}^{-1}$.  Using the associative rule, we have

$$
\left( \left( \textbf{ST} \right)^{-1} \textbf{S} \right) \textbf{T} = \textbf{I}
$$

Since the inverse matrix is unique, this means that

$$
\textbf{T}^{-1} = \left( \textbf{ST} \right)^{-1} \textbf{S}
$$

Now multiplying on the right by $\textbf{S}^{-1}$ we have

$$
(\textbf{S} \textbf{T})^{-1} = \textbf{T}^{-1} \textbf{S}^{-1}
$$
as required.

Consider the transpose conjugate of the  product of two unitary matrices, $\textbf{U}$ and $\textbf{V}$:

$$
\begin{eqnarray}
\left( \textbf{UV} \right)^{\dagger} & = & \textbf{V}^{\dagger} \textbf{U}^{\dagger} \\
& = & \textbf{V}^{-1} \textbf{U}^{-1} \\
& = & \left( \textbf{UV} \right)^{-1}
\end{eqnarray}
$$
So the product of two unitary matrices is unitary as well.

Now consider the transpose conjugate of the product of two Hermitian matrices, $\textbf{S}$ and $\textbf{T}$:

$$
\begin{eqnarray}
\left( \textbf{ST} \right)^{\dagger} & = & \textbf{T}^{\dagger} \textbf{S}^{\dagger} \\
& = & \textbf{TS}
\end{eqnarray}
$$
Thus the product of two Hermitian matrices will remain Hermitian if the two matrices commute.

The sum of two unitary matrices is not necessarily unitary.  Consider the sum of the identity matrix with itself.  The matrix $2 \textbf{I}$ is not unitary.

The sum of two Hermitian matrices will be Hermitian because 

$$
\begin{eqnarray}
\left( \textbf{S} + \textbf{T} \right)^{\dagger} & = & \textbf{S}^{\dagger} + \textbf{T}^{\dagger} \\
& = & \textbf{S} + \textbf{T}
\end{eqnarray}
$$

## Problem A.12

Because $\textbf{U} \textbf{U}^{\dagger} = \textbf{U} \textbf{U}^{-1}$, we have

$$
\begin{eqnarray}
\left( \textbf{U} \textbf{U}^{\dagger} \right)_{ij} & = & \delta_{ij} \\
\left( \sum_k u_{ik} u_{jk}^* \right) & = & \delta_{ij} \\
\braket{u_j}{u_i} & = & \delta_{ij}
\end{eqnarray}
$$

and so the rows are orthonormal.  The columns can be shown to be orthonormal by noting that the transpose of a unitary matrix is also unitary.

## Problem A.13

A matrix is Hermitian iff $\textbf{H} = \textbf{H}^{\dagger}$.  This means that $\textrm{det}(\textbf{H}) = \textrm{det}(\textbf{H}^{\dagger})$.  But because the determinant of a matrix is invariant under the transpose operation, this means that $\textrm{det}(\textbf{H}) = \textrm{det}(\textbf{H}^*)$.  Now, since a determinant is simply a polynomial in the matrix entries, this means that the determinant of the complex conjugate matrix is equal to the complex conjugate of the determinant of the original matrix.  This means that $\textrm{det}(\textbf{H}) = \left( \textrm{det}(\textbf{H})\right)^*$.  This then implies that $\textrm{det}(\textbf{H})$ must be real.

For a unitary matrix we have
$$
\begin{eqnarray}
\textrm{det}(\textbf{U}) & = & \textrm{det}(\tilde{\textbf{U}}) \\
& = & \textrm{det}(\textbf{U}^{\dagger})^* \\
& = & \textrm{det}(\textbf{U}^{-1})^* \\
& = & \frac{1}{\textrm{det}(\textbf{U})^*}
\end{eqnarray}
$$
This implies that $|\textrm{det}(\textbf{U})|^2 = 1$ and so $\textrm{det}(\textbf{U})$ has unit modulus.

For an orthogonal matrix we have
$$
\begin{eqnarray}
\textrm{det}(\textbf{O}) & = & \textrm{det}(\tilde{\textbf{O}}) \\
& = & \textrm{det}(\textbf{O}^{-1}) \\
& = & \frac{1}{\textrm{det}(\textbf{O})}
\end{eqnarray}
$$
This implies that $\textrm{det}(\textbf{O})^2 = 1$.  Now, since all the entries of an orthogonal matrix are real, this means that the determinant must be real as well.  The only real numbers satisfying this equation is then $\textrm{det}(\textbf{O}) = \pm 1$.

## Problem A.14

### Part a.

$$
\textbf{R}_1 = \left( \begin{matrix}
\cos \theta & -\sin \theta & 0 \\
\sin \theta & \cos \theta & 0 \\
0 & 0 & 1
\end{matrix} \right)
$$

### Part b.

This matrix will rotate the $x$-axis into the $y$-axis, the $y$-axis into the $z$-axis, and the $z$-axis into the $x$-axis:
$$
\textbf{R}_2 = \left( \begin{matrix}
0 & 0 & 1 \\
1 & 0 & 0 \\
0 & 1 & 0 \\
\end{matrix} \right)
$$

### Part c.

$$
\textbf{R}_3 = \left( \begin{matrix}
1 & 0 & 0 \\
0 & 1 & 0 \\
0 & 0 & -1 \\
\end{matrix} \right)
$$

### Part d.

$$
\textbf{R}_1 \tilde{\textbf{R}}_1 = \left( \begin{matrix}
\cos \theta & -\sin \theta & 0 \\
\sin \theta & \cos \theta & 0 \\
0 & 0 & 1
\end{matrix} \right) \left( \begin{matrix}
\cos \theta & \sin \theta & 0 \\
-\sin \theta & \cos \theta & 0 \\
0 & 0 & 1
\end{matrix} \right) = \left( \begin{matrix}
\cos^2 \theta + \sin^2 \theta & \cos \theta \sin \theta - \cos \theta \sin \theta & 0 \\
\cos \theta \sin \theta - \cos \theta \sin \theta & \cos^2 \theta + \sin^2 \theta & 0 \\
0 & 0 & 1 \\
\end{matrix} \right) = \left( \begin{matrix}
1 & 0 & 0 \\
0 & 1 & 0 \\
0 & 0 & 1 \\
\end{matrix} \right)
$$

$$
\textrm{det}(\textbf{R}_1) = \cos^2 \theta + \sin^2 \theta = 1
$$

$$
\textbf{R}_2 \tilde{\textbf{R}}_2 = \left( \begin{matrix}
0 & 0 & 1 \\
1 & 0 & 0 \\
0 & 1 & 0 \\
\end{matrix} \right) \left( \begin{matrix}
0 & 1 & 0 \\
0 & 0 & 1 \\
1 & 0 & 0 \\
\end{matrix} \right) = \left( \begin{matrix}
1 & 0 & 0 \\
0 & 1 & 0 \\
0 & 0 & 1 \\
\end{matrix} \right)
$$

$$
\textrm{det}(\textbf{R}_2) = 1
$$

$$
\textbf{R}_3 \tilde{\textbf{R}}_3 = \left( \begin{matrix}
1 & 0 & 0 \\
0 & 1 & 0 \\
0 & 0 & -1 \\
\end{matrix} \right) \left( \begin{matrix}
1 & 0 & 0 \\
0 & 1 & 0 \\
0 & 0 & -1 \\
\end{matrix} \right) = \left( \begin{matrix}
1 & 0 & 0 \\
0 & 1 & 0 \\
0 & 0 & 1 \\
\end{matrix} \right)
$$

$$
\textrm{det}(\textbf{R}_3) = -1
$$

In [27]:
def R1(theta):
    return np.array([
        [np.cos(theta), -np.sin(theta), 0],
        [np.sin(theta), np.cos(theta), 0],
        [0, 0, 1]
    ])

In [29]:
R1(.123) @ R1(.123).T

array([[ 1.00000000e+00, -1.95932709e-18,  0.00000000e+00],
       [-1.95932709e-18,  1.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00,  1.00000000e+00]])

In [30]:
np.linalg.det(R1(.123))

1.0

In [31]:
R2 = np.array([
    [0, 0, 1],
    [1, 0, 0],
    [0, 1, 0]
])

In [32]:
R2 @ R2.T

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [33]:
np.linalg.det(R2)

1.0

In [34]:
R3 = np.array([
    [1, 0, 0],
    [0, 1, 0],
    [0, 0, -1]
])

In [35]:
R3 @ R3.T

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [36]:
np.linalg.det(R3)

-1.0