# Appendix

In [1]:
import numpy as np

Invisible Latex commands are in this cell.

$$\newcommand{\ket}[1]{\left|{#1}\right\rangle}$$
$$\newcommand{\bra}[1]{\left\langle{#1}\right|}$$
$$\newcommand{\braket}[2]{\left\langle{#1}\middle|{#2}\right\rangle}$$
$$\newcommand{\norm}[1]{\left\lVert#1\right\rVert}$$

## Problem A.1

### Part a.

Yes, the subset of all vectors with $a_z = 0$ is a vector space.  Since the the original set is a vector space, the properties of vector addition and multiplication all hold, but we must show that the subspace is closed.  Here, note that the sum of any two vectors in the subspace will have $a_z = 0$ as well since the sum can be done component-wise.  Furthermore, scalar multiplication is closed since we can again perform the operation component-wise and this will maintain $a_z = 0$.  Finally, the null vector is in this subspace since the null vector has $a_z = 0$, and the inverse vectors are in the subspace since the inverses can be found component-wise and $-0 = 0 = a_z$.

The dimension of the subspace is 2 since it is spanned by the basis vectors $\hat{i}$ and $\hat{j}$.

### Part b.

The subspace of all vectors with $a_z = 1$ is not a subspace because it is not closed under vector addition or scalar multiplication.  For example, $2 \cdot \hat{k}$ is not in the subspace even though $\hat{k}$ is.  Furthermore the subspace does not have a null vector since the null vector must have $a_z = 0$.

### Part c.

The subset of all vectors whose components are all equal is a vector space.

Consider $\textbf{a} = a \hat{i} + a \hat{j} + a \hat{k}$ and $\textbf{b} = b \hat{i} + b \hat{j} + b \hat{k}$.  Then $\textbf{a} + \textbf{b} = (a + b) \hat{i} + (a + b) \hat{j} + (a + b) \hat{k}$.  All the components are equal, so the vector stays in the subspace.  Similarly, $c \textbf{a} = ca \hat{i} + ca \hat{j} + ca \hat{k}$.  All the components are equal so the vector stays in the subspace.  Thus the subspace is closed under addition and multiplication.  Finally, the null vector exists in this subspace and the inverse vectors all also have the same components and so exist in the subspace.

## Problem A.2

### Part a.

This set is a vector space.  The sum of two polynomials of degree $N$ is also a polynomial of degree $N$ or less, so the set is closed under addition.  Multiplying a polynomial of degree $N$ by a scalar is also a polynomial of degree $N$ or less, so the set is closed under multiplication.  Furthermore, $0$ exists as a null vector, and the inverse vectors also exist by taking the coefficients of the polynomials and multilpying them by $-1$.

### Part b.

The set of even polynomials is also a vector space since the sum of two even polynomials is also an even polynomial (nor does multiplication by a scalar change the evenness of the polynomial).  Furthermore this subset contains the null vector and every inverse vector.

### Part c.

The subset of polynomials with the leading coefficient equal to 1 is not a vector space since the sum of two such polynomials has a leading coefficient equal to 2 and is therefore not in the space.

### Part d.

The subset of polynomials with the value 0 at $x = 1$ is a vector space.  We can write such polynomials as

$$
a = (x - 1) \sum_{i = 0}^{N - 1} a_i x^i
$$

Now, the sum of two such polynomials is

\begin{eqnarray}
\textbf{a} + \textbf{b} & = & (x - 1) \sum_{i = 0}^{N - 1} a_i x^i + (x - 1) \sum_{i = 0}^{N - 1} b_i x^i \\
 & = & (x - 1) \sum_{i = 0}^{N - 1} (a_i + b_i) x^i
\end{eqnarray}

and so is closed under vector addition.  Similarly, multiplying such a polynomial by a scalar results in

\begin{eqnarray}
c \textbf{a} & = & c (x - 1) \sum_{i = 0}^{N - 1} a_i x^i \\
& = & (x - 1) \sum_{i = 0}^{N - 1} (c a_i) x^i
\end{eqnarray}

and so is closed under scalar multiplication.  The space contains the null vector since setting the $a_i = 0$ results in a polynomial which is 0 at $x = 1$.  Finally, the space contains all inverse vectors by setting the coefficients equal to $-a_i$.

### Part e.

The subset of polynomials with the value 1 at $x = 0$ is not a vector space since it does not contain the null vector nor is it closed under addition since the sum of two such polynomials will have the value 2 at $x = 0$.

## Problem A.3

We may write the vector $\ket{\alpha}$ as

$$
\ket{\alpha} = \sum_i a_i \ket{e_i}
$$

Now, suppose there were some other component representation in this basis.  Then we could write 

$$
\ket{\alpha} = \sum_i b_i \ket{e_i}
$$

with $a_i \neq b_i$ for some $i$.  But now consider the difference between these two representations:

$$
\sum_i a_i \ket{e_i} - \sum_i b_i \ket{e_i} = \sum_i (a_i - b_i) \ket{e_i} \neq 0
$$

since by assumption there is some component that is different.  But we must have that this difference equals zero since $\ket{\alpha} - \ket{\alpha} = 0$ and the null vector has zeros in all components.

## Problem A.4

$$
\norm{e_1} = 2
$$

$$
\ket{e_1^{\prime}} = \frac{1}{2}(1 + i) \hat{i} + \frac{1}{2} \hat{j} + \frac{i}{2} \hat{k}
$$

$$
\braket{e_1^{\prime}}{e_2} = \frac{i}{2} (1 - i) + \frac{3}{2} - \frac{i}{2} = \frac{1}{2}(i + 1 - 3 - i) = 2
$$

$$
\ket{e_2} - \braket{e_1^{\prime}}{e_2} = i \hat{i} + 3 \hat{j} + \hat{k} - 2((1 + i) \hat{i} + \hat{j} + i \hat{k}) 
= -\hat{i} + 2 \hat{j} + (1 - i) \hat{k}
$$

$$
\norm{\ket{e_2} - \braket{e_1^{\prime}}{e_2}} = \sqrt{1 + 4 + 2} = \sqrt{7}
$$

$$
\ket{e_2^{\prime}} = -\frac{1}{\sqrt{7}} \hat{i} + \frac{2}{\sqrt{7}} \hat{j} + \frac{1 - i}{\sqrt{7}} \hat{k}
$$

$$
\braket{e_1^{\prime}}{e_3} = 14
$$

$$
\braket{e_2^{\prime}}{e_3} = 8 \sqrt{7}
$$

$$
\ket{e_3} - \braket{e_1^{\prime}}{e_3} - \braket{e_2^{\prime}}{e_3} =
28 \hat{j} - 7((1 + i) \hat{i} + \hat{j} + i \hat{k}) - 8(-\hat{i} + 2\hat{j} + (1 - i) \hat{k}) =
(1 - 7i) \hat{i} + 5 \hat{j} + (-8 + i)\hat{k}
$$

$$
\norm{\ket{e_3} - \braket{e_1^{\prime}}{e_3} - \braket{e_2^{\prime}}{e_3}} = \sqrt{140}
$$

$$
\ket{e_3^{\prime}} = \frac{1}{2 \sqrt{35}} ((1 - 7i) \hat{i} + 5 \hat{j} + (-8 + i) \hat{k})
$$

In [2]:
e1 = np.array([1 + 1j, 1, 1j])
e2 = np.array([1j, 3, 1])
e3 = np.array([0, 28, 0])

In [3]:
e1prime = e1 / np.linalg.norm(e1)
e1prime

array([0.5+0.5j, 0.5+0.j , 0. +0.5j])

In [4]:
e2prime = (e2 - np.vdot(e1prime, e2) * e1prime) / np.linalg.norm(e2 - np.vdot(e1prime, e2) * e1prime)

In [5]:
np.allclose(e2prime, np.array([-1 / np.sqrt(7), 2 / np.sqrt(7), (1 - 1j) / np.sqrt(7)]))

True

In [6]:
e3prime = ((e3 - np.vdot(e1prime, e3) * e1prime - np.vdot(e2prime, e3) * e2prime) /
    np.linalg.norm(e3 - np.vdot(e1prime, e3) * e1prime - np.vdot(e2prime, e3) * e2prime))

In [7]:
np.allclose(e3prime, 1 / (2 * np.sqrt(35)) * np.array([1 - 7j, 5, -8 + 1j]))

True

## Problem A.5

Let

$$
\ket{\gamma} \equiv \ket{\beta} - \frac{\braket{\alpha}{\beta}}{\braket{\alpha}{\alpha}} \ket{\alpha}.
$$

Now consider the norm of $\gamma$:

\begin{eqnarray}
\braket{\gamma}{\gamma} & = & \left( \bra{\beta} - \frac{\braket{\beta}{\alpha}}{\braket{\alpha}{\alpha}} \bra{\alpha} \right) \left( \ket{\beta} - \frac{\braket{\alpha}{\beta}}{\braket{\alpha}{\alpha}} \ket{\alpha} \right) \\
& = & \braket{\beta}{\beta} - \frac{\braket{\alpha}{\beta}}{\braket{\alpha}{\alpha}} \braket{\beta}{\alpha} - \frac{\braket{\beta}{\alpha}}{\braket{\alpha}{\alpha}} \braket{\alpha}{\beta} + \frac{\braket{\beta}{\alpha} \braket{\alpha}{\beta}}{\braket{\alpha}{\alpha}^2} \braket{\alpha}{\alpha} \\
& = & \braket{\beta}{\beta} + \frac{\braket{\beta}{\alpha} \braket{\alpha}{\beta}}{\braket{\alpha}{\alpha}}
\end{eqnarray}

Now, note that $\braket{\gamma}{\gamma} \geq 0$, so

$$
\braket{\alpha}{\alpha} \braket{\beta}{\beta} \geq \left| \braket{\alpha}{\beta} \right|^2
$$

as required.

## Problem A.6

$$
\braket{\alpha}{\beta} = (1 - i)(4 - i) - i(2 - 2i) = 1 - 7i
$$

$$
\braket{\beta}{\alpha} = 1 + 7i
$$

$$
\braket{\alpha}{\alpha} = 4
$$

$$
\braket{\beta}{\beta} = 25
$$

$$
\cos \theta = \sqrt{\frac{(1 + 7i)(1 - 7i)}{4 \times 25}} = \frac{1}{\sqrt{2}}
$$

And so $\theta = \pi / 4$.

In [8]:
alpha = np.array([1 + 1j, 1, 1j])
beta = np.array([4 - 1j, 0, 2 - 2j])

In [9]:
np.allclose(
    np.pi / 4, 
    np.arccos(np.sqrt(np.vdot(alpha, beta) * np.vdot(beta, alpha) /
                      (np.linalg.norm(alpha)**2 * np.linalg.norm(beta)**2))),
)

True

## Problem A.7

\begin{eqnarray}
\norm{\ket{\alpha} + \ket{\beta}}^2 & = & \left( \bra{\alpha} + \bra{\beta} \right) \left(\ket{\alpha} + \ket{\beta}\right) \\
& = & \braket{\alpha}{\alpha} + \braket{\beta}{\beta} + \braket{\alpha}{\beta} + \braket{\beta}{\alpha} \\
& = & \norm{\alpha}^2 + \norm{\beta}^2 + \braket{\alpha}{\beta} + \braket{\alpha}{\beta}^*
\end{eqnarray}

Now note that by the Schwarz inequality $|\braket{\alpha}{\beta}| \leq \norm{\alpha} \norm{\beta}$.  This implies that

\begin{eqnarray}
\norm{\ket{\alpha} + \ket{\beta}}^2 & \leq & \norm{\alpha}^2 + \norm{\beta}^2 + 2 \norm{\alpha} \norm{\beta} \\
& \leq & \left( \norm{\alpha} + \norm{\beta} \right)^2
\end{eqnarray}

Therefore $\norm{\ket{\alpha} + \ket{\beta}} \leq \norm{\alpha} + \norm{\beta}$ as required.

## Problem A.8

In [10]:
A = np.array([[-1, 1, 1j], [2, 0, 3], [2j, -2j, 2]])
B = np.array([[2, 0, -1j], [0, 1, 0], [1j, 3, 2]])

### Part a.

$$
\textbf{A} + \textbf{B} = \left(
\begin{matrix}
1 & 1 & 0 \\
2 & 1 & 3 \\
3i & 3 - 2i & 4 \\
\end{matrix} \right)
$$

In [11]:
A + B

array([[1.+0.j, 1.+0.j, 0.+0.j],
       [2.+0.j, 1.+0.j, 3.+0.j],
       [0.+3.j, 3.-2.j, 4.+0.j]])

### Part b.

$$
\textbf{A} \textbf{B} = \left(
\begin{matrix}
-3 & 1 + 3i & 3i \\
4 + 3i & 9 & 6 - 2i \\
6i & 6 - 2i & 6 \\
\end{matrix} \right)
$$

In [12]:
A @ B

array([[-3.+0.j,  1.+3.j,  0.+3.j],
       [ 4.+3.j,  9.+0.j,  6.-2.j],
       [ 0.+6.j,  6.-2.j,  6.+0.j]])

### Part c.

$$
\textbf{B} \textbf{A} = \left(
\begin{matrix}
0 & 0 & 0 \\
2 & 0 & 3 \\
6 + 3i & -3i & 12 \\
\end{matrix} \right)
$$

This implies that

$$
\left[ \textbf{A}, \textbf{B} \right] = \left(
\begin{matrix}
-3 & 1 + 3i & 3i \\
2 + 3i & 9 & 3 - 2i \\
-6 + 3i & 6 + i & -6 \\
\end{matrix}
\right)
$$

In [13]:
A@B - B@A

array([[-3.+0.j,  1.+3.j,  0.+3.j],
       [ 2.+3.j,  9.+0.j,  3.-2.j],
       [-6.+3.j,  6.+1.j, -6.+0.j]])

### Part d.

$$
\tilde{\textbf{A}} = \left(
\begin{matrix}
-1 & 2 & 2i \\
1 & 0 & -2i \\
i & 3 & 2 \\
\end{matrix} \right)
$$

In [14]:
np.transpose(A)

array([[-1.+0.j,  2.+0.j,  0.+2.j],
       [ 1.+0.j,  0.+0.j, -0.-2.j],
       [ 0.+1.j,  3.+0.j,  2.+0.j]])

### Part e.

$$
\textbf{A}^* = \left(
\begin{matrix}
-1 & 1 & -i \\
2 & 0 & 3 \\
-2i & 2i & 2 \\
\end{matrix} \right)
$$

In [15]:
np.conj(A)

array([[-1.-0.j,  1.-0.j,  0.-1.j],
       [ 2.-0.j,  0.-0.j,  3.-0.j],
       [ 0.-2.j, -0.+2.j,  2.-0.j]])

### Part f.

$$
\textbf{A}^\dagger = \left(
\begin{matrix}
-1 & 2 & -2i \\
1 & 0 & 2i \\
-i & 3 & 2 \\
\end{matrix} \right)
$$

In [16]:
np.matrix.getH(A)

array([[-1.-0.j,  2.-0.j,  0.-2.j],
       [ 1.-0.j,  0.-0.j, -0.+2.j],
       [ 0.-1.j,  3.-0.j,  2.-0.j]])

### Part g.

$$
\textrm{det}(\textbf{B}) = 
2 \left| \begin{matrix} 1 & 0 \\ 3 & 2 \end{matrix} \right|
-i \left| \begin{matrix} 0 & 1 \\ i & 3 \end{matrix} \right|
= 4 - 1 = 3
$$

In [17]:
np.linalg.det(B)

(2.9999999999999996+0j)

### Part h.

The matrix of cofactors is given by

$$
\textbf{C} = \left( \begin{matrix}
2 & 0 & -i \\
-3i & 5 & -6 \\
i & 0 & 2 \\
\end{matrix} \right)
$$

and so the inverse is

$$
\textbf{B}^{-1} = \frac{1}{3} \left( \begin{matrix}
2 & -3i & i \\
0 & 3 & 0 \\
-i & -6 & 2 \\
\end{matrix} \right)
$$

We have

$$
\textbf{B}^{-1} \textbf{B} = \frac{1}{3} \left( \begin{matrix}
2 & -3i & i \\
0 & 3 & 0 \\
-i & -6 & 2 \\
\end{matrix} \right) \left( \begin{matrix}
2 & 0 & -i \\
0 & 1 & 0 \\
i & 3 & 2 \\
\end{matrix} \right)
= \left( \begin{matrix}
1 & 0 & 0 \\
0 & 1 & 0 \\
0 & 0 & 1 \\
\end{matrix} \right)
$$

as required.

In [18]:
np.linalg.inv(B)

array([[ 0.66666667+0.j        ,  0.        -1.j        ,
         0.        +0.33333333j],
       [ 0.        +0.j        ,  1.        +0.j        ,
         0.        +0.j        ],
       [ 0.        -0.33333333j, -2.        -0.j        ,
         0.66666667+0.j        ]])

$\textbf{A}$ does not have an inverse because its determinant is zero:

$$
\textrm{det}(\textbf{A}) = - \left| \begin{matrix} 0 & 3 \\ -2i & 1 \end{matrix} \right|
- \left| \begin{matrix} 2 & 3 \\ 2i & 2 \end{matrix} \right|
+ i \left| \begin{matrix} 2 & 0 \\ 2i & -2i \\ \end{matrix} \right|
= -6i -4 + 6i + 4 = 0
$$

In [19]:
np.linalg.det(A)

0j

## Problem A.9

### Part a.

$$
\textbf{A} \textbf{a} = \left( \begin{matrix}
-1 & 1 & i \\
2 & 0 & 3 \\
2i & -2i & 2 \\
\end{matrix} \right) \left( \begin{matrix}
i \\
2i \\
2 \\
\end{matrix} \right) = \left( \begin{matrix}
3i \\
6 + 2 i \\
6 \\
\end{matrix} \right)
$$

In [20]:
a = np.array([[1j], [2j], [2]])
b = np.array([[2], [1 - 1j], [0]])

In [21]:
np.matmul(A, a)

array([[0.+3.j],
       [6.+2.j],
       [6.+0.j]])

### Part b.

$$
\textbf{a}^{\dagger} \textbf{b} = \left( \begin{matrix}
-i & -2i & 2 \\ \end{matrix} \right) \left( \begin{matrix}
2 \\
1 - i \\
0 \\
\end{matrix} \right) = -2i - 2i - 2 = -2 - 4i
$$

In [22]:
np.dot(np.conj(a.T), b)

array([[-2.-4.j]])

### Part c.

$$
\tilde{\textbf{a}} \textbf{B} \textbf{b} = \left( \begin{matrix}
i & 2i & 2 \end{matrix} \right) \left( \begin{matrix}
2 & 0 & -i \\
0 & 1 & 0 \\
i & 3 & 2 \\
\end{matrix} \right) \left( \begin{matrix}
2 \\
1 - i \\
0 \\
\end{matrix} \right) = \left( \begin{matrix}
i & 2i & 2 \end{matrix} \right) \left( \begin{matrix}
4 \\
1 - i \\
3 - i \\
\end{matrix} \right) = 8 + 4i
$$

In [23]:
np.matmul(a.T, np.matmul(B, b))

array([[8.+4.j]])

### Part d.

$$
\textbf{a} \textbf{b}^{\dagger} = \left( \begin{matrix}
i \\
2i \\
2 \\
\end{matrix} \right) \left( \begin{matrix}
2 & 1 + i & 0 \\
\end{matrix} \right) = \left( \begin{matrix}
2i & -1 + i & 0 \\
4i & -2 + 2i & 0 \\
4 & 2 + 2i & 0 \\
\end{matrix} \right)
$$

In [24]:
np.matmul(a, np.conj(b.T))

array([[ 0.+2.j, -1.+1.j,  0.+0.j],
       [ 0.+4.j, -2.+2.j,  0.+0.j],
       [ 4.+0.j,  2.+2.j,  0.+0.j]])

## Problem A.10

### Part a.

Consider an arbitrary element of the matrix $\textbf{T}$, $T_{ij}$.  In general we will have that $T_{ij} \neq T_{ji}$.  Now suppose it is possible to write $\textbf{T}$ as a sum of a symmetrix matrix $\textbf{S}$ and an antisymmetric matrix $\textbf{A}$.  Then we have

$$
\begin{eqnarray}
T_{ij} & = & S_{ij} + A_{ij}, \\
T_{ji} & = & S_{ij} - A_{ij}
\end{eqnarray}
$$

Solving for $S_{ij}$ and $A_{ij}$ we find

$$
\begin{eqnarray}
S_{ij} = \frac{1}{2} \left( T_{ij} + T_{ji} \right) \\
A_{ij} = \frac{1}{2} \left( T_{ij} - T_{ji} \right) \\
\end{eqnarray}
$$
By inspection it can be verified that $\textbf{S}$ is indeed symmetric and $\textbf{A}$ is antisymmetric.

Thus by construction it is possible to write any matrix as a sum of a symmetric and antisymmetric matrix.

### Part b.

An arbitrary term of the matrix $\textbf{T}$ can be written

$$
T_{ij} = a_{ij} + b_{ij} i.
$$

Construct a matrix $\textbf{R}$ whose components are given by $R_{ij} = a_{ij}$ and a matrix $\textbf{M}$ whose components are given by $M_{ij} = b_{ij} i$.  Then $\textbf{R}$ is a real matrix and $\textbf{M}$ is an imaginary matrix and any matrix can be written as the sum of the two.

### Part c.

Consider an arbitrary element of the matrix $\textbf{T}$, $T_{ij}$.  Suppose that it is possible to write $\textbf{T}$ as the sum of a Hermitian matrix $\textbf{H}$ and a skew-Hermitian matrix $\textbf{K}$.  Then we have

$$
\begin{eqnarray}
T_{ij} & = & H_{ij} + K_{ij} \\
T_{ji}^* & = & H_{ij} - K_{ij} \\
\end{eqnarray}
$$

Solving for $H_{ij}$ and $K_{ij}$ we find

$$
\begin{eqnarray}
H_{ij} & = & \frac{1}{2} \left( T_{ij} + T_{ji}^* \right) \\
K_{ij} & = & \frac{1}{2} \left( T_{ij} - T_{ji}^* \right)
\end{eqnarray}
$$
By inspection it can be verified that $\textbf{H}$ is indeed Hermitian and $\textbf{K}$ is skew-Hermitian.

Thus by construction it is possible to write any matrix as a sum of a Hermitian and skew-Hermitian matrix.

## Problem A.11

Let us prove that $\widetilde{\textbf{S} \textbf{T}} = \tilde{\textbf{T}} \tilde{\textbf{S}}$.  Consider an arbitrary element of $\widetilde{\textbf{S} \textbf{T}}$:

$$
\begin{eqnarray}
\left(\widetilde{\textbf{S} \textbf{T}}\right)_{ij} & = & \sum_k S_{jk} T_{ki} \\
& = & \sum_k T_{ki} S_{jk} \\
& = & \sum_k \tilde{T}_{ik} \tilde{S}_{kj} \\
& = & \left( \tilde{\textbf{T}} \tilde{\textbf{S}} \right)_{ij}
\end{eqnarray}
$$

Now let us prove that $(\textbf{ST})^{\dagger} = \textbf{T}^{\dagger} \textbf{S}^{\dagger}$.  Consider an arbitrary element:

$$
\begin{eqnarray}
\left( \textbf{ST} \right)^{\dagger}_{ij} & = & \left( \sum_k S_{ik} T_{kj} \right)^{\dagger} \\
& = & \sum_k S_{jk}^* T_{ki}^* \\
& = & \sum_k T_{ki}^* S_{jk}^* \\
& = & \left( \textbf{T}^{\dagger} \textbf{S}^{\dagger} \right)_{ij}
\end{eqnarray}
$$

Let us prove that $(\textbf{S} \textbf{T})^{-1} = \textbf{T}^{-1} \textbf{S}^{-1}$.  Using the associative rule, we have

$$
\left( \left( \textbf{ST} \right)^{-1} \textbf{S} \right) \textbf{T} = \textbf{I}
$$

Since the inverse matrix is unique, this means that

$$
\textbf{T}^{-1} = \left( \textbf{ST} \right)^{-1} \textbf{S}
$$

Now multiplying on the right by $\textbf{S}^{-1}$ we have

$$
(\textbf{S} \textbf{T})^{-1} = \textbf{T}^{-1} \textbf{S}^{-1}
$$
as required.

Consider the transpose conjugate of the  product of two unitary matrices, $\textbf{U}$ and $\textbf{V}$:

$$
\begin{eqnarray}
\left( \textbf{UV} \right)^{\dagger} & = & \textbf{V}^{\dagger} \textbf{U}^{\dagger} \\
& = & \textbf{V}^{-1} \textbf{U}^{-1} \\
& = & \left( \textbf{UV} \right)^{-1}
\end{eqnarray}
$$
So the product of two unitary matrices is unitary as well.

Now consider the transpose conjugate of the product of two Hermitian matrices, $\textbf{S}$ and $\textbf{T}$:

$$
\begin{eqnarray}
\left( \textbf{ST} \right)^{\dagger} & = & \textbf{T}^{\dagger} \textbf{S}^{\dagger} \\
& = & \textbf{TS}
\end{eqnarray}
$$
Thus the product of two Hermitian matrices will remain Hermitian if the two matrices commute.

The sum of two unitary matrices is not necessarily unitary.  Consider the sum of the identity matrix with itself.  The matrix $2 \textbf{I}$ is not unitary.

The sum of two Hermitian matrices will be Hermitian because 

$$
\begin{eqnarray}
\left( \textbf{S} + \textbf{T} \right)^{\dagger} & = & \textbf{S}^{\dagger} + \textbf{T}^{\dagger} \\
& = & \textbf{S} + \textbf{T}
\end{eqnarray}
$$

## Problem A.12

Because $\textbf{U} \textbf{U}^{\dagger} = \textbf{U} \textbf{U}^{-1}$, we have

$$
\begin{eqnarray}
\left( \textbf{U} \textbf{U}^{\dagger} \right)_{ij} & = & \delta_{ij} \\
\left( \sum_k u_{ik} u_{jk}^* \right) & = & \delta_{ij} \\
\braket{u_j}{u_i} & = & \delta_{ij}
\end{eqnarray}
$$

and so the rows are orthonormal.  The columns can be shown to be orthonormal by noting that the transpose of a unitary matrix is also unitary.

## Problem A.13

A matrix is Hermitian iff $\textbf{H} = \textbf{H}^{\dagger}$.  This means that $\textrm{det}(\textbf{H}) = \textrm{det}(\textbf{H}^{\dagger})$.  But because the determinant of a matrix is invariant under the transpose operation, this means that $\textrm{det}(\textbf{H}) = \textrm{det}(\textbf{H}^*)$.  Now, since a determinant is simply a polynomial in the matrix entries, this means that the determinant of the complex conjugate matrix is equal to the complex conjugate of the determinant of the original matrix.  This means that $\textrm{det}(\textbf{H}) = \left( \textrm{det}(\textbf{H})\right)^*$.  This then implies that $\textrm{det}(\textbf{H})$ must be real.

For a unitary matrix we have
$$
\begin{eqnarray}
\textrm{det}(\textbf{U}) & = & \textrm{det}(\tilde{\textbf{U}}) \\
& = & \textrm{det}(\textbf{U}^{\dagger})^* \\
& = & \textrm{det}(\textbf{U}^{-1})^* \\
& = & \frac{1}{\textrm{det}(\textbf{U})^*}
\end{eqnarray}
$$
This implies that $|\textrm{det}(\textbf{U})|^2 = 1$ and so $\textrm{det}(\textbf{U})$ has unit modulus.

For an orthogonal matrix we have
$$
\begin{eqnarray}
\textrm{det}(\textbf{O}) & = & \textrm{det}(\tilde{\textbf{O}}) \\
& = & \textrm{det}(\textbf{O}^{-1}) \\
& = & \frac{1}{\textrm{det}(\textbf{O})}
\end{eqnarray}
$$
This implies that $\textrm{det}(\textbf{O})^2 = 1$.  Now, since all the entries of an orthogonal matrix are real, this means that the determinant must be real as well.  The only real numbers satisfying this equation is then $\textrm{det}(\textbf{O}) = \pm 1$.

## Problem A.14

### Part a.

$$
\textbf{R}_1 = \left( \begin{matrix}
\cos \theta & -\sin \theta & 0 \\
\sin \theta & \cos \theta & 0 \\
0 & 0 & 1
\end{matrix} \right)
$$

### Part b.

This matrix will rotate the $x$-axis into the $y$-axis, the $y$-axis into the $z$-axis, and the $z$-axis into the $x$-axis:
$$
\textbf{R}_2 = \left( \begin{matrix}
0 & 0 & 1 \\
1 & 0 & 0 \\
0 & 1 & 0 \\
\end{matrix} \right)
$$

### Part c.

$$
\textbf{R}_3 = \left( \begin{matrix}
1 & 0 & 0 \\
0 & 1 & 0 \\
0 & 0 & -1 \\
\end{matrix} \right)
$$

### Part d.

$$
\textbf{R}_1 \tilde{\textbf{R}}_1 = \left( \begin{matrix}
\cos \theta & -\sin \theta & 0 \\
\sin \theta & \cos \theta & 0 \\
0 & 0 & 1
\end{matrix} \right) \left( \begin{matrix}
\cos \theta & \sin \theta & 0 \\
-\sin \theta & \cos \theta & 0 \\
0 & 0 & 1
\end{matrix} \right) = \left( \begin{matrix}
\cos^2 \theta + \sin^2 \theta & \cos \theta \sin \theta - \cos \theta \sin \theta & 0 \\
\cos \theta \sin \theta - \cos \theta \sin \theta & \cos^2 \theta + \sin^2 \theta & 0 \\
0 & 0 & 1 \\
\end{matrix} \right) = \left( \begin{matrix}
1 & 0 & 0 \\
0 & 1 & 0 \\
0 & 0 & 1 \\
\end{matrix} \right)
$$

$$
\textrm{det}(\textbf{R}_1) = \cos^2 \theta + \sin^2 \theta = 1
$$

$$
\textbf{R}_2 \tilde{\textbf{R}}_2 = \left( \begin{matrix}
0 & 0 & 1 \\
1 & 0 & 0 \\
0 & 1 & 0 \\
\end{matrix} \right) \left( \begin{matrix}
0 & 1 & 0 \\
0 & 0 & 1 \\
1 & 0 & 0 \\
\end{matrix} \right) = \left( \begin{matrix}
1 & 0 & 0 \\
0 & 1 & 0 \\
0 & 0 & 1 \\
\end{matrix} \right)
$$

$$
\textrm{det}(\textbf{R}_2) = 1
$$

$$
\textbf{R}_3 \tilde{\textbf{R}}_3 = \left( \begin{matrix}
1 & 0 & 0 \\
0 & 1 & 0 \\
0 & 0 & -1 \\
\end{matrix} \right) \left( \begin{matrix}
1 & 0 & 0 \\
0 & 1 & 0 \\
0 & 0 & -1 \\
\end{matrix} \right) = \left( \begin{matrix}
1 & 0 & 0 \\
0 & 1 & 0 \\
0 & 0 & 1 \\
\end{matrix} \right)
$$

$$
\textrm{det}(\textbf{R}_3) = -1
$$

In [25]:
def R1(theta):
    return np.array([
        [np.cos(theta), -np.sin(theta), 0],
        [np.sin(theta), np.cos(theta), 0],
        [0, 0, 1]
    ])

In [26]:
R1(.123) @ R1(.123).T

array([[ 1.00000000e+00, -1.95932709e-18,  0.00000000e+00],
       [-1.95932709e-18,  1.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00,  1.00000000e+00]])

In [27]:
np.linalg.det(R1(.123))

1.0

In [28]:
R2 = np.array([
    [0, 0, 1],
    [1, 0, 0],
    [0, 1, 0]
])

In [29]:
R2 @ R2.T

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [30]:
np.linalg.det(R2)

1.0

In [31]:
R3 = np.array([
    [1, 0, 0],
    [0, 1, 0],
    [0, 0, -1]
])

In [32]:
R3 @ R3.T

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [33]:
np.linalg.det(R3)

-1.0

## Problem A.15

$$
\textbf{T}_x = \left( \begin{matrix}
1 & 0 & 0 \\
0 & \cos \theta & -\sin \theta \\
0 & \sin \theta & \cos \theta \\
\end{matrix} \right)
$$

$$
\textbf{T}_y = \left( \begin{matrix}
-\cos \theta & 0 & \sin \theta \\
0 & 1 & 0 \\
-\sin \theta & 0 & \cos \theta \\
\end{matrix} \right)
$$

$$
\textbf{S} = \left( \begin{matrix}
0 & -1 & 0 \\
1 & 0 & 0 \\
0 & 0 & 1 \\
\end{matrix} \right)
$$

$$
\textbf{S} \textbf{T}_x \textbf{S}^{-1} = \left( \begin{matrix}
0 & -1 & 0 \\
1 & 0 & 0 \\
0 & 0 & 1 \\
\end{matrix} \right) \left( \begin{matrix}
1 & 0 & 0 \\
0 & \cos \theta & -\sin \theta \\
0 & \sin \theta & \cos \theta \\
\end{matrix} \right) \left( \begin{matrix}
0 & 1 & 0 \\
-1 & 0 & 0 \\
0 & 0 & 1 \\
\end{matrix} \right)
$$

$$
\implies \textbf{S} \textbf{T}_x \textbf{S}^{-1} = \left( \begin{matrix}
0 & -\cos \theta & \sin \theta \\
1 & 0 & 0 \\
0 & \sin \theta & \cos \theta \\
\end{matrix} \right) \left( \begin{matrix}
0 & 1 & 0 \\
-1 & 0 & 0 \\
0 & 0 & 1 \\
\end{matrix} \right)
$$

$$
\implies \textbf{S} \textbf{T}_x \textbf{S}^{-1} = \left( \begin{matrix}
\cos \theta & 0 & \sin \theta \\
0 & 1 & 0 \\
-\sin \theta & 0 & \cos \theta \\
\end{matrix} \right)
$$

This transformation is therefore equivalent to reflecting about the $x$-axis and then rotating by $-\theta$ about the $y$-axis.

Now for $\textbf{T}_y$:

$$
\textbf{S} \textbf{T}_y \textbf{S}^{-1} = \left( \begin{matrix}
0 & -1 & 0 \\
1 & 0 & 0 \\
0 & 0 & 1 \\
\end{matrix} \right) \left( \begin{matrix}
-\cos \theta & 0 & \sin \theta \\
0 & 1 & 0 \\
-\sin \theta & 0 & \cos \theta \\
\end{matrix} \right) \left( \begin{matrix}
0 & 1 & 0 \\
-1 & 0 & 0 \\
0 & 0 & 1 \\
\end{matrix} \right)
$$

$$
\implies \textbf{S} \textbf{T}_y \textbf{S}^{-1} = \left( \begin{matrix}
0 & -1 & 0 \\
-\cos \theta & 0 & \sin \theta \\
-\sin \theta & 0 & \cos \theta \\
\end{matrix} \right) \left( \begin{matrix}
0 & 1 & 0 \\
-1 & 0 & 0 \\
0 & 0 & 1 \\
\end{matrix} \right)
$$

$$
\implies \textbf{S} \textbf{T}_y \textbf{S}^{-1} = \left( \begin{matrix}
1 & 0 & 0 \\
0 & -\cos \theta & \sin \theta \\
0 & -\sin \theta & \cos \theta \\
\end{matrix} \right)
$$

This transformation is therefore equivalent to reflecting about the $y$-axis and rotating by $-\theta$ about the $x$-axis.

In [34]:
S = np.array([
    [0, -1, 0],
    [1, 0, 0],
    [0, 0, 1]
])

In [35]:
theta = 0.123

In [36]:
Tx = np.array([
    [1, 0, 0],
    [0, np.cos(theta), -np.sin(theta)],
    [0, np.sin(theta), np.cos(theta)],
])

In [37]:
Ty = np.array([
    [-np.cos(theta), 0, np.sin(theta)],
    [0, 1, 0],
    [-np.sin(theta), 0, np.cos(theta)],
])

In [38]:
S @ Tx

array([[ 0.        , -0.99244503,  0.12269009],
       [ 1.        ,  0.        ,  0.        ],
       [ 0.        ,  0.12269009,  0.99244503]])

In [39]:
S @ Tx @ np.linalg.inv(S)

array([[ 0.99244503,  0.        ,  0.12269009],
       [ 0.        ,  1.        ,  0.        ],
       [-0.12269009,  0.        ,  0.99244503]])

In [40]:
S @ Ty

array([[ 0.        , -1.        ,  0.        ],
       [-0.99244503,  0.        ,  0.12269009],
       [-0.12269009,  0.        ,  0.99244503]])

In [41]:
S @ Ty @ np.linalg.inv(S)

array([[ 1.        ,  0.        ,  0.        ],
       [ 0.        , -0.99244503,  0.12269009],
       [ 0.        , -0.12269009,  0.99244503]])

## Problem A.16

We wish to show that given two bases $e$ and $f$, then for any matrices $\textbf{A}^e \textbf{B}^e = \textbf{C}^e$ implies that $\textbf{A}^f \textbf{B}^f = \textbf{C}^f$.  Let us consider the product $\textbf{A}^f \textbf{B}^f$:

$$
\begin{eqnarray}
\textbf{A}^f \textbf{B}^f & = & \textbf{S} \textbf{A}^e \textbf{S}^{-1} \textbf{S} \textbf{B}^e \textbf{S}^{-1} \\
& = & \textbf{S} \textbf{A}^e \textbf{B}^e \textbf{S}^{-1} \\
& = & \textbf{S} \textbf{C}^e \textbf{S}^{-1} \\
& = & \textbf{C}^f
\end{eqnarray}
$$

Now we must show that if $\textbf{S}$ is unitary and $\textbf{H}^e$ is Hermitian then $\textbf{H}^f$ is Hermitian as well.  We have

$$
\begin{eqnarray}
\textbf{H}^f & = & \textbf{S} \textbf{H}^e \textbf{S}^{-1} \\
& = & \textbf{S} \textbf{H}^e \textbf{S}^{\dagger}
\end{eqnarray}
$$

Now consider the adjoint:

$$
\begin{eqnarray}
\textbf{H}^{\dagger} & = & \left( \textbf{S} \textbf{H}^e \textbf{S}^{-1} \right)^{\dagger} \\
& = & \textbf{S}^{-1 \dagger} \textbf{H}^{e \dagger} \textbf{S}^{\dagger} \\
& = & \textbf{S} \textbf{H}^e \textbf{S}^{\dagger}
\end{eqnarray}
$$

And so $\textbf{H}^f = \textbf{H}^{f \dagger}$ meaning that $\textbf{H}^f$ is Hermitian.

Lastly we must show that $\textbf{S}$ carries an orthonormal basis into another orthonormal basis if and only if it is unitary.  Consider the transformation $\textbf{S}$ wihch transforms basis $e$ into $f$.  We thus have

$$
\ket{f_i} = \textbf{S} \ket{e_i}
$$

Now, if $e$ is an orthonormal basis then we have

$$
\braket{e_i}{e_j} = \delta_{ij}.
$$

Let us first suppose that $\textbf{S}$ is unitary.  Now consider the dot product of two basis vectors in the $f$ basis:

$$
\begin{eqnarray}
\braket{f_i}{f_j} & = & \bra{e_i} \textbf{S}^{\dagger} \textbf{S} \ket{e_j} \\
& = & \braket{e_i}{e_j} \\
& = & \delta_{ij}
\end{eqnarray}
$$

So the assumption that $\textbf{S}$ is unitary implies that $\textbf{S}$ carries one orthonormal basis into another.

Now let us prove the other direction.  Let us suppose that $\textbf{S}$ carries $e$ into another orthonormal basis.  This means that

$$
\begin{eqnarray}
\braket{f_i}{f_j} & = & \delta_{ij} \\
\bra{e_i} \textbf{S}^{\dagger} \textbf{S} \ket{e_j} & = & \delta_{ij}
\end{eqnarray}
$$

However, we already know that $\braket{e_i}{e_j} = \delta_{ij}$, so $\textbf{S}^{\dagger} \textbf{S} = I$, which implies that $\textbf{S}^{\dagger} = \textbf{S}^{-1}$ and therefore $\textbf{S}$ is unitary.

## Problem A.17

Let us write out the first trace explicitly:

$$
\textrm{Tr}(\textbf{T}_1 \textbf{T}_2) = \sum_{i, k} \textbf{T}_{1, ik} \textbf{T}_{2, ki}
$$

Now consider the second trace:

$$
\begin{eqnarray}
\textrm{Tr}(\textbf{T}_2 \textbf{T}_1) & = & \sum_{i, k} \textbf{T}_{2, ik} \textbf{T}_{1, ki} \\
& = & \sum_{k, i} \textbf{T}_{1, ki} \textbf{T}_{2, ik} \\
\end{eqnarray}
$$
where we can do this second step because each individual term is just the product of two scalars and therefore commutes.  Now because the summation indices are dummy indices we can simply rename them:
$$
\begin{eqnarray}
\textrm{Tr}(\textbf{T}_2 \textbf{T}_1) & = & \sum_{i, k} \textbf{T}_{1, ik} \textbf{T}_{2, ki} \\
& = & \textrm{Tr}(\textbf{T}_1 \textbf{T}_2)
\end{eqnarray}
$$

As a counterexample to show that the trace is not conserved for all permutations of the product of three matrices, consider the following:

$$
\textbf{T}_1 = \left( \begin{matrix}
0 & 1 \\
1 & 0 \\
\end{matrix} \right)
$$

$$
\textbf{T}_2 = \left( \begin{matrix}
1 & 1 \\
0 & 0 \\
\end{matrix} \right)
$$

$$
\textbf{T}_3 = \left( \begin{matrix}
1 & 0 \\
1 & 0 \\
\end{matrix} \right)
$$

Now we have
$$
\textbf{T}_1 \textbf{T}_2 \textbf{T}_3 = \left( \begin{matrix}
0 & 1 \\
1 & 0 \\
\end{matrix} \right) \left( \begin{matrix}
1 & 1 \\
0 & 0 \\
\end{matrix} \right) \left( \begin{matrix}
1 & 0 \\
1 & 0 \\
\end{matrix} \right) = \left( \begin{matrix}
0 & 1 \\
1 & 0 \\
\end{matrix} \right) \left( \begin{matrix}
2 & 0 \\
0 & 0 \\
\end{matrix} \right) = \left( \begin{matrix}
0 & 0 \\
2 & 0 \\
\end{matrix} \right).
$$
So we have
$$
\textrm{Tr}(\textbf{T}_1 \textbf{T}_2 \textbf{T}_3) = 0
$$

Now consider the following product:
$$
\textbf{T}_2 \textbf{T}_1 \textbf{T}_3 = \left( \begin{matrix}
1 & 1 \\
0 & 0 \\
\end{matrix} \right) \left( \begin{matrix}
0 & 1 \\
1 & 0 \\
\end{matrix} \right) \left( \begin{matrix}
1 & 0 \\
1 & 0 \\
\end{matrix} \right) = \left( \begin{matrix}
1 & 1 \\
0 & 0 \\
\end{matrix} \right) \left( \begin{matrix}
1 & 0 \\
1 & 0 \\
\end{matrix} \right) = \left( \begin{matrix}
2 & 0 \\
0 & 0 \\
\end{matrix} \right).
$$
So we have $\textrm{Tr}(\textbf{T}_2 \textbf{T}_1 \textbf{T}_3) = 2$.

In [42]:
T1 = np.array([[0, 1], [1, 0]])
T2 = np.array([[1, 1], [0, 0]])
T3 = np.array([[1, 0], [1, 0]])

In [43]:
np.trace(T1 @ T2 @ T3)

0

In [44]:
np.trace(T2 @ T1 @ T3)

2

## Problem A.18

To find the eigenvalues we must solve the following determinant:

$$
\begin{vmatrix}
\cos \theta - \lambda & -\sin \theta \\
\sin \theta & \cos \theta - \lambda \\
\end{vmatrix} = 0
$$

This implies that we must find the $\lambda$ that satisfies the equation

$$
(\cos \theta - \lambda)^2  +\sin^2 \theta = 0
$$

$$
\implies \lambda^2 - 2 \lambda \cos \theta + 1 = 0
$$

$$
\begin{eqnarray}
\implies \lambda & = & \frac{1}{2} \left(2 \cos \theta \pm \sqrt{4 \cos^2 \theta - 4} \right) \\
& = & \cos \theta \pm \sqrt{\cos^2 \theta - 1} \\
& = & \cos \theta \pm \sqrt{- \sin^2 \theta} \\
& = & \cos \theta \pm i \sin \theta
\end{eqnarray}
$$

Thus we only have a real solution iff $\sin \theta = 0$, which means that we must have $\theta \in \{0, \pi\}$.

We can simplify the general case of complex eigenvalues with $\lambda = e^{\pm i \theta}$.  To find the eigenvectors, we have in the positive case

$$
\left( \begin{matrix}
\cos \theta & -\sin \theta \\
\sin \theta & \cos \theta \\
\end{matrix} \right) \left( \begin{matrix}
v_1 \\
v_2 \\
\end{matrix} \right) = e^{i \theta} \left( \begin{matrix}
v_1 \\
v_2 \\
\end{matrix} \right)
$$
This implies the following set of equations:
$$
\begin{eqnarray}
\cos \theta v_1 - \sin \theta v_2 & = & e^{i \theta} v_1 \\
\sin \theta v_1 + \cos \theta v_2 & = & e^{i \theta} v_2
\end{eqnarray}
$$
$$
\begin{eqnarray}
\implies v_1 & = & - \frac{\sin \theta v_2}{e^{i \theta} - \cos \theta} \\
& = & -\frac{v_2}{i} \\
& = & i v_2
\end{eqnarray}
$$
And so the first eigenvector is
$$
a^{(1)} = \frac{1}{\sqrt{2}} \left( \begin{matrix}
1 \\
-i
\end{matrix} \right)
$$
To find the second eigenvector, we now have
$$
\left( \begin{matrix}
\cos \theta & -\sin \theta \\
\sin \theta & \cos \theta \\
\end{matrix} \right) \left( \begin{matrix}
v_1 \\
v_2 \\
\end{matrix} \right) = e^{-i \theta} \left( \begin{matrix}
v_1 \\
v_2 \\
\end{matrix} \right)
$$
which similarly implies
$$
\begin{eqnarray}
\cos \theta v_1 - \sin \theta v_2 & = & e^{-i \theta} v_1 \\
\sin \theta v_1 + \cos \theta v_2 & = & e^{-i \theta} v_2
\end{eqnarray}
$$
$$
\begin{eqnarray}
\implies v_1 & = & - \frac{\sin \theta v_2}{e^{-i \theta} - \cos \theta} \\
& = & \frac{v_2}{i} \\
& = & -i v_2
\end{eqnarray}
$$
And so the second eigenvector is
$$
a^{(2)} = \frac{1}{\sqrt{2}} \left( \begin{matrix}
1 \\
i
\end{matrix} \right)
$$

In [45]:
theta = 0.3
R = np.array([[np.cos(theta), -np.sin(theta)], [np.sin(theta), np.cos(theta)]])

In [46]:
a1 = np.array([1, -1j]) / np.sqrt(2)
a2 = np.array([1, 1j]) / np.sqrt(2)

In [47]:
np.matmul(R, a1)

array([0.67552491+0.20896434j, 0.20896434-0.67552491j])

In [48]:
np.exp(1j * theta) * a1

array([0.67552491+0.20896434j, 0.20896434-0.67552491j])

In [49]:
np.matmul(R, a2)

array([0.67552491-0.20896434j, 0.20896434+0.67552491j])

In [50]:
np.exp(-1j * theta) * a2

array([0.67552491-0.20896434j, 0.20896434+0.67552491j])

Now to find the similarity matrix $\textbf{S}$ we note that the matrix $\textbf{S}^{-1}$ has columns which are the eigenvectors:

$$
\textbf{S}^{-1} = \frac{1}{\sqrt{2}} \left( \begin{matrix}
1 & 1 \\
-i & i \\
\end{matrix} \right)
$$

The determinant of $\textbf{S}^{-1}$ is

$$
\textrm{det}(\textbf{S}^{-1}) = i
$$

so the matrix $\textbf{S}$ is

$$
\textbf{S} = \frac{1}{\sqrt{2}} \left( \begin{matrix}
1 & i \\
1 & -i
\end{matrix} \right)
$$

The diagonalization of $\textbf{T}$ will be

$$
\textbf{S} \textbf{T} \textbf{S}^{-1} = \frac{1}{2} \left( \begin{matrix}
1 & i \\
1 & -i
\end{matrix} \right) \left( \begin{matrix}
\cos \theta & -\sin \theta \\
\sin \theta & \cos \theta \\
\end{matrix} \right) \left( \begin{matrix}
1 & 1 \\
-i & i \\
\end{matrix} \right)
$$

$$
\textbf{S} \textbf{T} \textbf{S}^{-1} = \frac{1}{2} \left( \begin{matrix}
1 & i \\
1 & -i
\end{matrix} \right) \left( \begin{matrix}
\cos \theta + i \sin \theta & \cos \theta - i \sin \theta \\
\sin \theta - i \cos \theta & \sin \theta + i \cos \theta
\end{matrix} \right)
$$

$$
\textbf{S} \textbf{T} \textbf{S}^{-1} = \frac{1}{2} \left( \begin{matrix}
1 & i \\
1 & -i
\end{matrix} \right) \left( \begin{matrix}
e^{i \theta} & e^{-i \theta} \\
-i e^{i \theta} & i e^{-i \theta}
\end{matrix} \right)
$$

$$
\textbf{S} \textbf{T} \textbf{S}^{-1} = \left( \begin{matrix}
e^{i \theta} & 0 \\
0 & e^{-i \theta}
\end{matrix} \right)
$$

## Problem A.19

The eigenvalues are given by the solution to the equation

$$
\left| \begin{matrix}
1 - \lambda & 1 \\
0 & 1 - \lambda \\
\end{matrix} \right| = 0
$$

This implies that

$$
(1 - \lambda)^2 = 0
$$

and so the only eigenvalue is $\lambda = 1$, which has degeneracy 2.

The eigenvectors now must satisfy the equation

$$
\left( \begin{matrix}
1 & 1 \\
0 & 1 \\
\end{matrix} \right) \left( \begin{matrix}
v_1 \\
v_2 \\
\end{matrix} \right) = \left( \begin{matrix}
v_1 \\
v_2 \\
\end{matrix} \right)
$$

Thus we must have that

$$
v_2 = 0
$$

and we have no constraint on $v_1$.  This means that the original matrix $\textbf{M}$ is no diagonalizable because we cannot construct an eigenbasis that spans the vector space.

## Problem A.20

The characteristic equation can be written

$$
C_n \lambda^n + C_{n-1} \lambda^{n-1} + \cdots + C_0 = 0
$$

By the Leibniz formula, the determinant can be written

$$
\textrm{det}(\textbf{T} - \lambda \textbf{I}) = \sum_{\sigma} \left( \textrm{sgn}(\sigma) \prod_{i=1}^n T_{i \sigma_i} - \lambda \delta_{i \sigma_i} \right),
$$
where $\sigma$ represents a permutation and $\sigma_i$ represents the $i^{\textrm{th}}$ term of that permutation and the sum is taken over all possible permutations of the range $\{1, \ldots, n \}$.

Let us first consider the $C_n$ coefficient.  To find its value we must identify the $\lambda^n$ term.  Note that the Kronecker delta will vanish for at least one value of $i$ for all permutations except the first permutation, which is just the original order $[1, \ldots, n]$.  Considering only that permutation, we find that the $\lambda^n$ term is simply

$$
C_n = (-1)^n.
$$

Now consider the second coefficient, $C_{n-1}$, which is associated with the $\lambda^{n-1}$ term.  Once again, observe that the Kronecker delta will vanish for at least one value of $i$ for all permutations except the first permutation, which is just the original order $[1, \ldots, n]$.  But if the Kronecker delta vanishes for one value of $i$, it must vanish for some other value of $i$ because the first $i$ must occupy the space for this other value of $i$.  So in fact, at least *two* Kronecker deltas must vanish.  Thus, in order to obtain a $\lambda^{n-1}$ term, only one permutation is possible: the original order of $[1, \ldots, n]$.  Fixing this permutation, and examining the Leibniz formula, we find

$$
\begin{eqnarray}
C_{n-1} & = & \sum_{i=1}^n (-1)^{n-1} T_{ii} \\
& = & (-1)^{n-1} \textrm{Tr}(\textbf{T})
\end{eqnarray}
$$

For the last coefficient, $C_0$, note that any cross term in the Leibniz formula with the Kronecker delta will contain a power of $\lambda$.  The term without any powers of $\lambda$ can then just be written

$$
\begin{eqnarray}
C_0 & = & \sum_{\sigma} \left( \textrm{sgn}(\sigma) \prod_{i=1}^n T_{i \sigma_i} \right) \\
& = & \textrm{det}(\textbf{T}) 
\end{eqnarray}
$$

## Problem A.21

Because it is a polynomial, the characteristic equation may be factored as such:

$$
\prod_{i = 1}^n (\lambda_i - \lambda) = 0
$$

Consider now the term without any powers of $\lambda$.  This must be the $C_0$ term, which in the previous problem was found to be $\textrm{det}{\textbf{T})$.  This term is then

$$
\begin{eqnarray}
\textrm{det}(\textbf{T}) & = & C_0 \\
& = & \prod_{i = 1}^n \lambda_i
\end{eqnarray}
$$

Now consider the $\lambda^{n-1}$ term, given by the coefficient $C_{n-1}$.  In the previous problem this was found to be equal to $(-1)^{n-1} \textrm{Tr}(\textbf{T})$.  Isolating the $\lambda^{n-1}$ terms of the factorized characteristic equation, we find

$$
\begin{eqnarray}
(-1)^{n-1} \textrm{Tr}(\textbf{T}) & = & C_{n-1} \\
& = & (-1)^{n-1} \sum_{i=1}^n \lambda_i
\end{eqnarray}
$$
which implies that
$$
\textrm{Tr}(\textbf{T}) = \sum_{i=1}^n \lambda_i.
$$

## Problem A.22

### Part a.

Suppose that $[\textbf{T}_1^e, \textbf{T}_2^e] = 0$.  This implies that

$$
\textbf{T}_1^e \textbf{T}_2^e - \textbf{T}_2^e \textbf{T}_1^e = 0
$$

Multiplying the left by $\textbf{S}$ and the right by $\textbf{S}^{-1}$, we have

$$
\begin{eqnarray}
\textbf{S} \textbf{T}_1^e \textbf{T}_2^e \textbf{S}^{-1} - \textbf{S} \textbf{T}_2^e \textbf{T}_1^e \textbf{S}^{-1} & = & 0 \\
\implies \textbf{S} \textbf{T}_1^e \textbf{S}^{-1} \textbf{S} \textbf{T}_2^e \textbf{S}^{-1} - \textbf{S} \textbf{T}_2^e \textbf{S}^{-1} \textbf{S} \textbf{T}_1^e \textbf{S}^{-1} & = & 0 \\
\implies \textbf{T}_1^f \textbf{T}_2^f - \textbf{T}_2^f \textbf{T}_1^f & = & 0
\end{eqnarray}
$$

### Part b.

If two matrices $\textbf{T}_1$ and $\textbf{T}_2$ are simultaneously diagonalizable, then there exists a matrix $\textbf{S}$ that will diagonalize both $\textbf{T}_1$ and $\textbf{T}_2$.  This means that we would have

$$
\begin{eqnarray}
\textbf{S} \textbf{T}_1 \textbf{S}^{-1} & = & \textbf{D}_1 \\
\textbf{S} \textbf{T}_2 \textbf{S}^{-1} & = & \textbf{D}_2,
\end{eqnarray}
$$

where $\textbf{D}_i$ represents some diagonal matrix.

Consider now the commutator of $\textbf{T}_1$ and $\textbf{T}_2$.  By multiplying $\textbf{S}$ on the left and $\textbf{S}^{-1}$ on the right, we get

$$
\begin{eqnarray}
[\textbf{T}_1, \textbf{T}_2] & = & \textbf{T}_1 \textbf{T}_2 - \textbf{T}_2 \textbf{T}_1 \\
& = & \textbf{S} \textbf{T}_1 \textbf{S}^{-1} \textbf{S} \textbf{T}_2 - \textbf{S} \textbf{T}_2 \textbf{S}^{-1} \textbf{S} \textbf{T}_1 \textbf{S}^{-1} \\
& = & \textbf{D}_1 \textbf{D}_2 - \textbf{D}_2 \textbf{D}_1 \\
& = & 0
\end{eqnarray}
$$

where we obtain the last step because any two diagonal matrices commute.

## Problem A.23

### Part a.

Let us calculate the commutator of $\textbf{M}$ with its Hermitian conjugate:

$$
\textbf{M} \textbf{M}^{\dagger} - \textbf{M}^{\dagger} \textbf{M} = \left( \begin{matrix}
1 & 1 \\
1 & i
\end{matrix} \right) \left( \begin{matrix}
1 & 1 \\
1 & -i
\end{matrix} \right) - \left( \begin{matrix}
1 & 1 \\
1 & -i
\end{matrix} \right) \left( \begin{matrix}
1 & 1 \\
1 & i
\end{matrix} \right)
$$

$$
\textbf{M} \textbf{M}^{\dagger} - \textbf{M}^{\dagger} \textbf{M} = \left( \begin{matrix}
2 & 1 - i \\
1 + i & 2 \\
\end{matrix} \right) - \left( \begin{matrix}
2 & 1 + i \\
1 & 2 \\
\end{matrix} \right)
$$

$$
\textbf{M} \textbf{M}^{\dagger} - \textbf{M}^{\dagger} \textbf{M} = \left( \begin{matrix}
0 & -2i \\
2i & 0 \\
\end{matrix} \right)
$$

So $\textbf{M}$ is not normal.

In [51]:
M = np.array([[1, 1], [1, 1j]])
M @ np.matrix.getH(M) - np.matrix.getH(M) @ M

array([[0.+0.j, 0.-2.j],
       [0.+2.j, 0.+0.j]])

### Part b.

First we need to find the eigenvalues:

$$
\left| \begin{matrix}
1 - \lambda & 1 \\
1 & i - \lambda \\
\end{matrix} \right| = 0
$$

$$
\begin{eqnarray}
\implies (1 - \lambda) (i - \lambda) - 1 & = & 0 \\
\implies \lambda^2 - (1 + i) \lambda - 1 + i & = & 0 \\
\implies \lambda & = & \frac{1}{2} \left( 1 + i \pm \sqrt{(1 + i)^2  +4 (1 - i)} \right) \\
\implies \lambda & = & \frac{1}{2} \left( 1 + i \pm \sqrt{4 - 2i} \right)
\end{eqnarray}
$$

The first eigenvector is then given by the solution to the equation

$$
\begin{eqnarray}
v_1^{(1)} + v_2^{(1)} & = & \frac{1}{2} \left( 1 + i + \sqrt{4 - 2i} \right) v_1^{(1)} \\
\implies v_2^{(1)} & = & \frac{1}{2} \left( -1 + i + \sqrt{4 - 2i} \right) v_1^{(1)}
\end{eqnarray}
$$

The second eigenvector is then

$$
\begin{eqnarray}
v_1^{(2)} + i v_2^{(2)} & = & \frac{1}{2} \left( 1 + i - \sqrt{4 - 2i} \right) v_2^{(2)} \\
\implies v_1^{(2)} & = & \frac{1}{2} \left(1 - i - \sqrt{4 - 2i} \right) v_2^{(2)}
\end{eqnarray}
$$

The inverse of the similarity matrix is then:

$$
\textbf{S}^{-1} = \left( \begin{matrix}
1 & -\frac{1}{2} \left(1 - i - \sqrt{4 - 2i} \right) \\
\frac{1}{2} \left(1 - i - \sqrt{4 - 2i} \right) & 1 \\
\end{matrix} \right)
$$

The determinant of this matrix is

$$
\begin{eqnarray}
\textrm{det}(\textbf{S}^{-1}) & = & 1 + \frac{1}{4} \left( 1 - i - \sqrt{4 - 2i} \right)^2 \\
& = & 1 + \frac{1}{4} \left( -2i + 4 - 2i - 2(1 - i) \sqrt{4 - 2i} \right) \\
& = & 1 + 1 - i - \frac{1}{2} (1 - i) \sqrt{4 - 2i} \\
& = & 2 - i - \frac{1}{2} (1 - i) \sqrt{4 - 2i} \\
\end{eqnarray}
$$

Since this determinant is non-zero, the matrix $\textbf{S}$ exists and the matrix $\textbf{M}$ is diagonalizable.

In [52]:
np.linalg.eigvals(M)

array([ 1.52908551+0.25706586j, -0.52908551+0.74293414j])

In [53]:
(-1 + 1j + np.sqrt(4 - 2j)) / 2

(0.5290855136357462+0.2570658641216772j)

In [54]:
(1 - 1j - np.sqrt(4 - 2j)) / 2

(-0.5290855136357462-0.2570658641216772j)

In [55]:
eigvectors = np.linalg.eig(M)[1]
eigvectors /= eigvectors[0, 0]

In [56]:
eigvectors

array([[ 1.        +0.j        , -0.52908551-0.25706586j],
       [ 0.52908551+0.25706586j,  1.        +0.j        ]])

In [57]:
np.linalg.det(eigvectors.T)

(1.2138486222425766+0.2720196495140689j)

In [58]:
2 - 1j - 1 / 2 * (1 - 1j) * np.sqrt(4 - 2j)

(1.2138486222425766+0.272019649514069j)

## Problem A.24

Suppose that for any vector $\ket{\gamma}$ we have

$$
\braket{\gamma}{\hat{T} \gamma} = \braket{\hat{T} \gamma}{\gamma}
$$

Since $\ket{\gamma}$ is an arbitrary vector, we can write it as the sum of two other arbitrary vectors:

$$
\ket{\gamma} \equiv \ket{\alpha} + \ket{\beta}
$$

Now, substituting,

$$
\left( \bra{\alpha} + \bra{\beta} \right) \left( \ket{\hat{T} \alpha} + \ket{\hat{T} \beta} \right) = \left( \bra{\hat{T} \alpha} + \bra{\hat{T} \beta} \right) \left( \ket{\alpha} + \ket{\beta} \right)
$$

$$
\implies \braket{\alpha}{\hat{T} \beta} + \braket{\beta}{\hat{T} \alpha} = \braket{\hat{T} \alpha}{\beta} + \braket{\hat{T} \beta}{\alpha}
$$

Now define another vector

$$
\ket{\gamma^{\prime}} \equiv \ket{alpha} + i \ket{\beta}
$$

This now implies

$$
\left( \bra{\alpha} - i \bra{\beta} \right) \left( \ket{\hat{T} \alpha} + i \ket{\hat{T} \beta} \right) = \left( \bra{\hat{T} \alpha} - i \bra{\hat{T} \beta} \right) \left( \ket{\alpha} + i \ket{\beta} \right)
$$

$$
\implies \braket{\alpha}{\hat{T} \beta} - \braket{\beta}{\hat{T} \alpha} = \braket{\hat{T} \alpha}{\beta} - \braket{\hat{T} \beta}{\alpha}
$$

Adding the result from using $\ket{\gamma}$ with the result from using vector $\ket{\gamma^{\prime}}$, we get

$$
\braket{\beta}{\hat{T} \alpha} = \braket{\hat{T} \beta}{\alpha}
$$

as required.

## Problem A.25

### Part a.

$$
\textbf{T}^{\dagger} = \left( \begin{matrix}
1 & 1 - i \\
1 + i & 0 \\
\end{matrix} \right) = \textbf{T}
$$

In [59]:
T = np.array([[1, 1-1j], [1+1j, 0]])

In [60]:
np.all(np.conj(T.T) == T)

True

### Part b.

The eigenvalues are found by solving the following equation:

$$
\left| \begin{matrix}
1 - \lambda & 1 - i \\
1 + i & -\lambda
\end{matrix} \right| = 0
$$

$$
\begin{eqnarray}
\implies \lambda^2 - \lambda - (1 - i)(1 + i) & = & 0 \\
\implies \lambda^2 - \lambda - 2 & = & 0 \\
\implies \lambda & = & \frac{1}{2} \left( 1 \pm \sqrt{1 + 8} \right) \\
\implies \lambda & \in & \{-1, 2\}
\end{eqnarray}
$$

In [61]:
np.linalg.eig(T)[0]

array([ 2.+1.04672831e-16j, -1.-1.04672831e-16j])

### Part c.

The eigenvector associated with the eigenvalue 2 is given by the solution to the equation

$$
\left( \begin{matrix}
1 & 1 - i \\
1 + i & 0
\end{matrix} \right) \left( \begin{matrix}
v_1 \\
v_2
\end{matrix} \right) = 2 \left( \begin{matrix}
v_1 \\
v_2
\end{matrix} \right)
$$

This implies the following system of equations:

$$
\begin{eqnarray}
v_1 + (1 - i) v_2 & = & 2 v_1 \\
(1 + i) v_1 = 2 v_2
\end{eqnarray}
$$

This yields the unnormalized eigenvector:

$$
\textbf{v}^{(2)} = \left( \begin{matrix}
1 \\
\frac{1}{2} (1 + i)
\end{matrix} \right)
$$

Normalizing yields

$$
\hat{\textbf{v}}^{(2)} = \left( \begin{matrix}
\sqrt{\frac{2}{3}} \\
\frac{1 + i}{\sqrt{6}}
\end{matrix} \right)
$$

The eigenvector associated with the eigenvalue -1 is given by the solution to the system of equations:

$$
\begin{eqnarray}
v_1 + (1 - i) v_2 & = & -v_1 \\
(1 + i) v_1 = -v_2
\end{eqnarray}
$$

This yields the unnormalized eigenvector

$$
\textbf{v}^{(-1)} = \left( \begin{matrix}
1 \\
-1 - i
\end{matrix} \right)
$$

Normalizing yields

$$
\hat{\textbf{v}}^{(-1)} = \left( \begin{matrix}
\frac{1}{\sqrt{3}} \\
-\frac{1 + i}{\sqrt{3}}
\end{matrix} \right)
$$

In [62]:
np.linalg.eig(T)[1]

array([[ 0.81649658+0.j        , -0.40824829+0.40824829j],
       [ 0.40824829+0.40824829j,  0.81649658+0.j        ]])

In [63]:
np.array([np.sqrt(2 / 3), (1 + 1j) / np.sqrt(6)])

array([0.81649658+0.j        , 0.40824829+0.40824829j])

In [64]:
np.array([1 / np.sqrt(3), -(1 + 1j) / np.sqrt(3)])

array([ 0.57735027+0.j        , -0.57735027-0.57735027j])

In [65]:
np.abs(1 / (np.linalg.eig(T)[1][0, 1] * np.sqrt(3)))

0.9999999999999998

In [66]:
np.linalg.eig(T)[1][:, 1] / (np.linalg.eig(T)[1][0, 1] * np.sqrt(3))

array([ 0.57735027+0.j        , -0.57735027-0.57735027j])

### Part d.

The inverse of the diagonalizing matrix is

$$
\textbf{S}^{-1} = \left( \begin{matrix}
\sqrt{\frac{2}{3}} & \frac{1}{\sqrt{3}} \\
\frac{1 + i}{\sqrt{6}} & -\frac{1 + i}{\sqrt{3}}
\end{matrix} \right)
$$

Now calculating $\textbf{S}$ we have

$$
\textbf{S} = \left( -\frac{\sqrt{2}}{3}(1 + i) - \frac{1}{3 \sqrt{2}} (1 + i) \right)^{-1} \left( \begin{matrix}
-\frac{1 + i}{\sqrt{3}} & -\frac{1}{\sqrt{3}} \\
-\frac{1 + i}{\sqrt{6}} & \sqrt{\frac{2}{3}}
\end{matrix} \right)
$$

So we have

$$
\textbf{S} = - \frac{\sqrt{2}}{1 + i} \left( \begin{matrix}
-\frac{1 + i}{\sqrt{3}} & -\frac{1}{\sqrt{3}} \\
\frac{1 + i}{\sqrt{6}} & \sqrt{\frac{2}{3}}
\end{matrix} \right)
$$

which reduces to

$$
\textbf{S} = \left( \begin{matrix}
\sqrt{\frac{2}{3}} & \frac{1 - i}{\sqrt{6}} \\
\frac{1}{\sqrt{3}} & -\frac{1 - i}{\sqrt{3}}
\end{matrix} \right)
$$

In [67]:
Sinv = np.array([[np.sqrt(2 / 3), 1 / np.sqrt(3)], [(1 + 1j) / np.sqrt(6), -(1 + 1j) / np.sqrt(3)]])

In [68]:
S = np.linalg.inv(Sinv)
S

array([[ 0.81649658+0.j        ,  0.40824829-0.40824829j],
       [ 0.57735027+0.j        , -0.57735027+0.57735027j]])

In [69]:
np.array([[np.sqrt(2 / 3), (1 - 1j) / np.sqrt(6)], [1 / np.sqrt(3), -(1 - 1j) / np.sqrt(3)]])

array([[ 0.81649658+0.j        ,  0.40824829-0.40824829j],
       [ 0.57735027+0.j        , -0.57735027+0.57735027j]])

Now let's check that we can use $\textbf{S}$ to diagonalize $\textbf{T}$:

$$
\textbf{S}\textbf{T}\textbf{S}^{-1} = \left( \begin{matrix}
\sqrt{\frac{2}{3}} & \frac{1 - i}{\sqrt{6}} \\
\frac{1}{\sqrt{3}} & -\frac{1 - i}{\sqrt{3}}
\end{matrix} \right) \left( \begin{matrix}
1 & 1 - i \\
1 + i & 0
\end{matrix} \right) \left( \begin{matrix}
\sqrt{\frac{2}{3}} & \frac{1}{\sqrt{3}} \\
\frac{1 + i}{\sqrt{6}} & -\frac{1 + i}{\sqrt{3}}
\end{matrix} \right)
$$

$$
\textbf{S}\textbf{T}\textbf{S}^{-1} = \left( \begin{matrix}
\frac{2 \sqrt{2}}{\sqrt{3}} & \sqrt{\frac{2}{3}}(1 - i) \\
-\frac{1}{\sqrt{3}} & \frac{1 - i}{\sqrt{3}}
\end{matrix} \right) \left( \begin{matrix}
\sqrt{\frac{2}{3}} & \frac{1}{\sqrt{3}} \\
\frac{1 + i}{\sqrt{6}} & -\frac{1 + i}{\sqrt{3}}
\end{matrix} \right)
$$

$$
\textbf{S}\textbf{T}\textbf{S}^{-1} = \left( \begin{matrix}
2 & 0 \\
0 & -1
\end{matrix} \right)
$$

### Part e.

We have

$$
\textrm{Tr}(\textbf{T}) = 1
$$

and

$$
\textrm{det}(\textbf{T}) = -2
$$

in both the original form and the diagonalized form.

## Problem A.26

### Part a.

We have

$$
\textrm{det}(\textbf{T}) = 2 \left| \begin{matrix}
2 & i \\
-i & 2 \\
\end{matrix} \right| - i \left| \begin{matrix}
-i & i \\
1 & 2 \\
\end{matrix} \right| + \left| \begin{matrix}
-i & 2 \\
1 & -i \\
\end{matrix} \right| = 6 - 3 - 3 = 0
$$

And for the trace we have

$$
\textrm{Tr}(\textbf{T}) = 2 + 2 + 2 = 6
$$

### Part b.

To find the eigenvalues we must solve the equation

$$
\left| \begin{matrix}
2 - \lambda & i & 1 \\
-i & 2 - \lambda & i \\
1 & -i & 2 - \lambda \\
\end{matrix} \right| = 0
$$

$$
\implies (2 - \lambda) \left| \begin{matrix}
2 - \lambda & i \\
-i & 2 - \lambda
\end{matrix} \right| - i \left| \begin{matrix}
-i & i \\
1 & 2 - \lambda \\
\end{matrix} \right| + \left| \begin{matrix}
-i & 2 - \lambda \\
1 & -i \\
\end{matrix} \right| = 0
$$

$$
\implies (2 - \lambda)^3 + 3 \lambda - 8 = 0
$$

$$
\implies \lambda^3 - 6 \lambda^2 + 9 \lambda = 0
$$

$$
\begin{eqnarray}
\implies \lambda_1 & = & 0 \\
\lambda_2 & = & 3 \\
\lambda_3 & = & 3
\end{eqnarray}
$$

where $\lambda = 3$ has a degeneracy of 2.  As is necessary, the sum of the eigenvalues is 6, consistent with the trace of $\textbf{T}$ and their product is 0, consistent with the determinant.  The diagonalized form of $\textbf{T}$ is

$$
\textbf{T}^{\prime} = \left( \begin{matrix}
3 & 0 & 0 \\
0 & 3 & 0 \\
0 & 0 & 0
\end{matrix} \right)
$$

### Part c.

Let us find the eigenvector associated with $\lambda_1 = 0$.  We must solve the following system of equations:

$$
\begin{eqnarray}
2 v_1 + i v_2 + v_3 & = & 0 \\
-i v_1 + 2 v_2 + i v_3 & = & 0 \\
v_1 - i v_2 + 2 v_3 & = & 0
\end{eqnarray}
$$

From the last equation we have
$$
v_1 = i v_2 - 2 v_3
$$

Substituting into the first we have

$$
2 (i v_2 - 2 v_3) + i v_2 + v_3 = 0
$$

$$
\implies 3i v_2 - 3 v_3 = 0
$$

$$
\implies v_3 = i v_2
$$

And now substituting back into the equation for $v_1$ we have

$$
v_1 = -i v_2
$$

Hence the first eigenvector is

$$
\textbf{v}^{(1)} = \left( \begin{matrix}
-i \\
1 \\
i
\end{matrix} \right)
$$

Normalizing gives

$$
\hat{\textbf{v}}^{(1)} = \frac{1}{\sqrt{3}} \left( \begin{matrix}
-i \\
1 \\
i
\end{matrix} \right)
$$

The next two are degenerate with each other and are solutions to the following system of equations:

$$
\begin{eqnarray}
2 v_1 + i v_2 + v_3 & = & 3 v_1 \\
-i v_1 + 2 v_2 + i v_3 & = & 3 v_2 \\
v_1 - i v_2 + 2 v_3 & = & 3 v_3
\end{eqnarray}
$$

Solving the first equation, we have

$$
v_1 = i v_2 + v_3
$$

Due to the degeneracy, this is the only constraint on the eigenvectors.  For the first, let us choose $v_2 = 0$ and $v_1 = 1$.  Then we have

$$
\textbf{v}^{(2)} = \left( \begin{matrix}
1 \\
0 \\
1 \\
\end{matrix} \right)
$$

Normalizing gives

$$
\hat{\textbf{v}}^{(2)} = \frac{1}{\sqrt{2}} \left( \begin{matrix}
1 \\
0 \\
1 \\
\end{matrix} \right)
$$

The last eigenvector must obey the above constraint but have an orthogonal component to the second eigenvector.  Let us choose $v_2 = i$ and $v_3 = 0$.  Then we have

$$
\textbf{v}^{\prime (3)} = \left( \begin{matrix}
-1 \\
i \\
0
\end{matrix} \right)
$$



But we would like this third eigenvector to be orthogonal to the second so let us orthogonalize it via the Gram-Schmidt process:

$$
\textbf{v}^{(3)} = \left( \begin{matrix}
-1 \\
i \\
0
\end{matrix} \right) - \braket{v^{(2)}}{v^{\prime (3)}}\ket{v^{(2)}} = \left( \begin{matrix}
-1 \\
i \\
0
\end{matrix} \right) + \frac{1}{2} \left( \begin{matrix}
1 \\
0 \\
1
\end{matrix} \right) = \left( \begin{matrix}
-\frac{1}{2} \\
i \\
\frac{1}{2}
\end{matrix} \right)
$$

Normalizing gives

$$
\hat{\textbf{v}}^{(3)} = \frac{1}{\sqrt{6}} \left( \begin{matrix}
-1 \\
2i \\
1
\end{matrix} \right)
$$

These eigenvectors are mutually orthogonal because

$$
\braket{\hat{\textbf{v}}^{(1)}}{\hat{\textbf{v}}^{(2)}} = \frac{i}{\sqrt{3}} \times \frac{1}{\sqrt{2}} + \frac{1}{\sqrt{3}} \times 0 - \frac{i}{\sqrt{3}} \times \frac{1}{\sqrt{2}} = 0
$$

$$
\braket{\hat{\textbf{v}}^{(1)}}{\hat{\textbf{v}}^{(3)}} = \frac{i}{\sqrt{3}} \times \left( -\frac{1}{\sqrt{6}} \right) + \frac{1}{\sqrt{3}} \times \frac{2i}{\sqrt{6}} - \frac{i}{\sqrt{3}} \times \frac{1}{\sqrt{6}} = 0
$$

$$
\braket{\hat{\textbf{v}}^{(2)}}{\hat{\textbf{v}}^{(3)}} = \frac{1}{\sqrt{2}} \times \left( -\frac{1}{\sqrt{6}} \right) + 0 \times \frac{2i}{\sqrt{6}} + \frac{1}{\sqrt{2}} \times \frac{1}{\sqrt{6}} = 0
$$

In [70]:
v1p = np.array([-1j, 1, 1j]) / np.sqrt(3)
v2p = np.array([1, 0, 1]) / np.sqrt(2)
v3p = np.array([-1, 2j, 1]) / np.sqrt(6)

In [71]:
print(np.linalg.norm(v1p))
print(np.linalg.norm(v2p))
print(np.linalg.norm(v3p))

1.0
0.9999999999999999
1.0


In [72]:
print(np.vdot(v1p, v2p))
print(np.vdot(v1p, v3p))
print(np.vdot(v2p, v3p))

0j
0j
0j


### Part d.

The inverse of the diagonalizing matrix has the eigenvectros in the columns:

$$
\textbf{S}^{-1} = \left( \begin{matrix}
-\frac{i}{\sqrt{3}} & \frac{1}{\sqrt{2}} & -\frac{1}{\sqrt{6}} \\
\frac{1}{\sqrt{3}} & 0 & \frac{2i}{\sqrt{6}} \\
\frac{i}{\sqrt{3}} & \frac{1}{\sqrt{2}} & \frac{1}{\sqrt{6}}
\end{matrix} \right)
$$

Since this matrix is unitary, the inverse is just the adjoint:

$$
\textbf{S} = \left( \begin{matrix}
\frac{i}{\sqrt{3}} & \frac{1}{\sqrt{3}} & -\frac{i}{\sqrt{3}} \\
\frac{1}{\sqrt{2}} & 0 & \frac{1}{\sqrt{2}} \\
\frac{i}{\sqrt{6}} & -\frac{2i}{\sqrt{6}} & \frac{1}{\sqrt{6}}
\end{matrix} \right)
$$

This means that

$$
\textbf{S} \textbf{T} \textbf{S}^{-1} = \left( \begin{matrix}
0 & 0 & 0 \\
0 & 3 & 0 \\
0 & 0 & 3
\end{matrix} \right)
$$

## Problem A.27

### Part a.

We would like to show that for an arbitrary unitary transformation, $\hat{U}$, we have

$$
\braket{\hat{U} \alpha}{\hat{U} \beta} = \braket{\alpha}{\beta}.
$$

The dot product on the left can be written in matrix notation as

$$
\begin{eqnarray}
\braket{\hat{U} \alpha}{\hat{U} \beta} & = & (\textbf{U} \alpha)^T (\textbf{U} \beta) \\
& = & \alpha^T \textbf{U}^T \textbf{U} \beta \\
& = & \alpha^T \textbf{U}^{-1} \textbf{U} \beta \\
& = & \alpha^T \beta \\
& = & \braket{\alpha}{\beta}
\end{eqnarray}
$$

### Part b.

We would now like to show that the eigenvalues of a unitary transform have unitary modulus.  Suppose the transformation has eigenvalue $\lambda$.  Then we have:

$$
\begin{eqnarray}
& \hat{U} \ket{\alpha} = \lambda \ket{\alpha} \\
\implies & \hat{U}^{-1} \hat{U} \ket{\alpha} = \lambda \hat{U}^{-1} \ket{\alpha} \\
\implies & \hat{U}^{-1} \ket{\alpha} = \frac{1}{\lambda} \ket{\alpha} \\
\implies & \hat{U}^{\dagger} \ket{\alpha} = \frac{1}{\lambda} \ket{\alpha} \\
\end{eqnarray}
$$



This now means that

$$
\braket{\alpha}{\hat{U} \alpha} = \frac{1}{\lambda} \braket{\alpha}{\alpha}
$$

But we can also write

$$
\begin{eqnarray}
\braket{\alpha}{\hat{U} \alpha} & = & \braket{\hat{U}^{\dagger} \alpha}{\alpha} \\
& = & \lambda^* \braket{\alpha}{\alpha} \\
\end{eqnarray}
$$

This implies that

$$
\frac{1}{\lambda} \braket{\alpha}{\alpha} = \lambda^* \braket{\alpha}{\alpha}
$$

$$
\implies \lambda \lambda^* = 1
$$

And so $|\lambda|^2 = 1$.

### Part c.

Now we wish to show that eigenvectors associated with distinct eigenvalues of a unitary transformation are orthogonal.  Consider two eigenvalues and eigenvectors:

$$
\begin{eqnarray}
\hat{U} \ket{\alpha} & = & \lambda_1 \ket{\alpha} \\
\hat{U} \ket{\beta} & = & \lambda_2 \ket{\beta}
\end{eqnarray}
$$

Now consider the dot product of the eigenvectors:

$$
\begin{eqnarray}
\braket{\beta}{\alpha} & = & \braket{\beta}{\hat{U}^{-1} \hat{U} \alpha} \\
& = & \braket{\hat{U} \beta}{\hat{U} \alpha} \\
& = & \lambda_1 \lambda_2^* \braket{\beta}{\alpha}
\end{eqnarray}
$$

Now let us suppose that $\braket{\beta}{\alpha}$ is nonzero (i.e., the two eigenvectors are not orthogonal).  Then we must have that

$$
\lambda_1 \lambda_2^* = 1
$$

But we know from Part b. that the modulus of each eigenvalue is unity.  The only way to multiply two complex numbers of unit modulus and get unity is if they are complex conjugates of one another.  (This can be seen by noting that the product of such a number with its complex conjugate will return unity, and the inverse is unique.)  This implies that $\lambda_1 = \lambda_2$.  But by assumption $\lambda_1 \neq \lambda_2$ so we have a contradiction and it must be the case that $\braket{\beta}{\alpha} = 0$.