In [1]:
from typing import List

import numpy as np

In [2]:
def check_group_membership(g: np.ndarray, group: List[np.ndarray], tol: float) -> bool:
    for elem in group:
        if np.allclose(g, elem, atol=tol, rtol=tol):
            return True
    return False


def generate_group(
    generators: List[np.ndarray], max_size: int = 1000, tol: float = 1e-6
) -> List[np.ndarray]:
    group = generators[:]
    
    while True:
        old_group = group[:]
        for g_1 in old_group:
            for g_2 in old_group:
                g = g_1 @ g_2
                if not check_group_membership(g, group, tol):
                    group.append(g)
        if len(old_group) == len(group) or len(group) > max_size:
            break
    
    return group

In [3]:
g = np.array([[np.sqrt(3) / 2, 1/2], [-1/2, np.sqrt(3) / 2]])

In [4]:
group = generate_group([g])

In [5]:
group

[array([[ 0.8660254,  0.5      ],
        [-0.5      ,  0.8660254]]),
 array([[ 0.5      ,  0.8660254],
        [-0.8660254,  0.5      ]]),
 array([[-1.11022302e-16,  1.00000000e+00],
        [-1.00000000e+00, -9.61481343e-17]]),
 array([[-0.5      ,  0.8660254],
        [-0.8660254, -0.5      ]]),
 array([[-0.8660254,  0.5      ],
        [-0.5      , -0.8660254]]),
 array([[-1.00000000e+00, -2.22044605e-16],
        [ 2.07170437e-16, -1.00000000e+00]]),
 array([[-0.8660254, -0.5      ],
        [ 0.5      , -0.8660254]]),
 array([[-0.5      , -0.8660254],
        [ 0.8660254, -0.5      ]]),
 array([[ 2.77555756e-16, -1.00000000e+00],
        [ 1.00000000e+00,  2.73570235e-16]]),
 array([[ 0.5      , -0.8660254],
        [ 0.8660254,  0.5      ]]),
 array([[ 0.8660254, -0.5      ],
        [ 0.5      ,  0.8660254]]),
 array([[ 1.00000000e+00,  3.84592537e-16],
        [-3.88578059e-16,  1.00000000e+00]])]

In [6]:
len(group)

12

In [7]:
g = np.array([[1 / np.sqrt(2), 1 / np.sqrt(2)], [-1 / np.sqrt(2), 1 / np.sqrt(2)]])

In [8]:
group = generate_group([g])

In [9]:
len(group)

8